-- lint: new-table
-- The lookups every sighting points to. Ported from the collector's spy
-- schema (013, 020, 021) without the operator and agency grouping, which is
-- Spy's work. Only tracks-loader writes here; everyone else reads tracks_api.

CREATE TABLE tracks.network (
    id SMALLINT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);
INSERT INTO tracks.network (id, code, name) VALUES (1, 'taboola', 'Taboola'), (2, 'newsbreak', 'NewsBreak Ads');

CREATE TABLE tracks.device (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
);
INSERT INTO tracks.device (code) VALUES ('desktop'), ('phone');

-- One page capture scrapes, named as in its targets file.
CREATE TABLE tracks.publisher (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id SMALLINT NOT NULL REFERENCES tracks.network(id),
    name TEXT NOT NULL UNIQUE,
    domain TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE tracks.placement (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE tracks.proxy_line (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
);

CREATE TABLE tracks.brand (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- The ad network account that pays for a campaign.
CREATE TABLE tracks.account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id SMALLINT NOT NULL REFERENCES tracks.network(id),
    external_id TEXT NOT NULL,
    org_external_id TEXT,  -- NewsBreak: the business that owns the account
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    UNIQUE (network_id, external_id)
);
CREATE INDEX account_org_idx ON tracks.account (network_id, org_external_id) WHERE org_external_id IS NOT NULL;

-- On NewsBreak Ads the campaign row is the ad set; parent_* is the NewsBreak
-- campaign above it, read from the landing link when the advertiser puts it there.
CREATE TABLE tracks.campaign (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id SMALLINT NOT NULL REFERENCES tracks.network(id),
    external_id TEXT NOT NULL,
    name TEXT,
    account_id INTEGER REFERENCES tracks.account(id),
    parent_external_id TEXT,
    parent_name TEXT,
    objective TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    UNIQUE (network_id, external_id)
);
CREATE INDEX campaign_account_idx ON tracks.campaign (account_id);

-- One ad image (or video), found by its file name (creative_key).
CREATE TABLE tracks.creative (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creative_key TEXT NOT NULL UNIQUE,
    image_url TEXT NOT NULL,
    format_type TEXT,
    video_duration INTEGER,
    thumb_dimensions TEXT,
    language TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX creative_last_seen_idx ON tracks.creative (last_seen_at DESC);

-- One creative with one headline. Description, CTA, brand and account keep
-- the latest value seen.
CREATE TABLE tracks.ad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creative_id INTEGER NOT NULL REFERENCES tracks.creative(id),
    headline TEXT NOT NULL,
    description TEXT,
    cta TEXT,
    brand_id INTEGER REFERENCES tracks.brand(id),
    account_id INTEGER REFERENCES tracks.account(id),
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);
CREATE UNIQUE INDEX ad_key ON tracks.ad (creative_id, md5(headline));
CREATE INDEX ad_brand_idx ON tracks.ad (brand_id);
CREATE INDEX ad_account_idx ON tracks.ad (account_id);

-- Where an ad's click goes first: host + path + campaign + item. One-time
-- click values are not part of the key; sample_url keeps the latest link.
CREATE TABLE tracks.link (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_key UUID NOT NULL UNIQUE,
    host TEXT NOT NULL,
    path TEXT NOT NULL,
    item_id TEXT,
    tracker TEXT,
    affiliate_network TEXT,
    params JSONB NOT NULL DEFAULT '{}'::jsonb,
    sample_url TEXT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX link_host_idx ON tracks.link (host);
CREATE INDEX link_first_seen_idx ON tracks.link (first_seen_at);

-- One ad id on an ad network (NewsBreak adId). Many can share one ad.
CREATE TABLE tracks.network_ad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network_id SMALLINT NOT NULL REFERENCES tracks.network(id),
    external_id TEXT NOT NULL,
    ad_id INTEGER NOT NULL REFERENCES tracks.ad(id),
    campaign_id INTEGER REFERENCES tracks.campaign(id),
    creative_external_id TEXT,
    name TEXT,
    started_at TIMESTAMPTZ,
    icon_url TEXT,
    layout TEXT,
    media_aspect TEXT,
    launch_option TEXT,
    iab_tier1 TEXT,
    iab_tier2 TEXT,
    landing_domain TEXT,
    disclaimer TEXT,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    UNIQUE (network_id, external_id)
);
CREATE INDEX network_ad_ad_idx ON tracks.network_ad (ad_id);
CREATE INDEX network_ad_campaign_idx ON tracks.network_ad (campaign_id);

-- The link key, as the loader computes it (LinkKey in load/lookups.go).
CREATE FUNCTION tracks.url_host(p_url TEXT) RETURNS TEXT LANGUAGE sql IMMUTABLE
AS $$ SELECT lower(COALESCE(substring(p_url FROM '^[a-zA-Z]+://([^/?#]+)'), '')) $$;

CREATE FUNCTION tracks.url_path(p_url TEXT) RETURNS TEXT LANGUAGE sql IMMUTABLE
AS $$ SELECT COALESCE(NULLIF(substring(p_url FROM '^[a-zA-Z]+://[^/?#]+([^?#]*)'), ''), '/') $$;

CREATE FUNCTION tracks.link_key(p_url TEXT, p_campaign TEXT, p_item TEXT) RETURNS UUID LANGUAGE sql IMMUTABLE
AS $$
    SELECT md5(tracks.url_host(p_url) || '|' || tracks.url_path(p_url) || '|' ||
               COALESCE(p_campaign, '') || '|' || COALESCE(p_item, ''))::uuid
$$;
