-- lint: new-table
-- One row per raw file in the archive. tracks-shipper inserts it once the
-- upload is verified; tracks-loader claims pending rows, oldest first, and
-- marks them loaded. Kept forever: it is the index of the archive.

CREATE TABLE tracks.raw_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,          -- <network>/<yyyy>/<mm>/<dd>/<hh>/capture-<instance>-<hhmm>[-n].ndjson.zst
    network TEXT NOT NULL,
    instance TEXT NOT NULL,
    minute TIMESTAMPTZ NOT NULL,       -- the minute capture wrote it in
    rows INTEGER NOT NULL,             -- scrapes in the file
    bytes BIGINT NOT NULL,             -- compressed size in the archive
    sha256 TEXT NOT NULL,              -- of the compressed file
    shipped_by TEXT NOT NULL,          -- the box that uploaded it
    archived_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    loaded_at TIMESTAMPTZ,
    scrapes INTEGER,                   -- scrapes loaded from it; equals rows when the books balance
    attempts SMALLINT NOT NULL DEFAULT 0,
    last_error TEXT,
    quarantined_at TIMESTAMPTZ         -- set aside after 3 failed loads; an alert, and replay once fixed
);
CREATE INDEX raw_file_pending_idx ON tracks.raw_file (minute, id) WHERE loaded_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX raw_file_minute_idx ON tracks.raw_file (minute);

-- The shipper's login records files and nothing else. The box setup creates
-- it before the first migration.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tracks_shipper') THEN
        GRANT USAGE ON SCHEMA tracks TO tracks_shipper;
        GRANT SELECT, INSERT, UPDATE (key) ON tracks.raw_file TO tracks_shipper;
    END IF;
END;
$$;
