-- lint: new-table
-- Click links as the feed served them, with the ad network's click values
-- still on, for Raposa: a visit needs a live link, and capture sees the ads
-- it looks for hundreds of times an hour. Was the collector's in-memory link
-- book (internal/sweeper/linkbook.go): 15 minutes, 40 per host, each link
-- handed out once. UNLOGGED: after a crash it starts empty and refills
-- within a minute.

CREATE UNLOGGED TABLE tracks.live_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host TEXT NOT NULL,                -- landing host without www. or secure.
    url TEXT NOT NULL,
    network TEXT NOT NULL,
    campaign_external_id TEXT,
    device TEXT NOT NULL,              -- desktop or phone
    publisher TEXT NOT NULL,
    page_url TEXT,                     -- the publisher page it was served on, for the referer
    ad_id INTEGER NOT NULL,
    creative_id INTEGER NOT NULL,
    seen_at TIMESTAMPTZ NOT NULL,
    taken_at TIMESTAMPTZ
);
CREATE INDEX live_link_host_idx ON tracks.live_link (host, seen_at DESC) WHERE taken_at IS NULL;
CREATE INDEX live_link_seen_idx ON tracks.live_link (seen_at);

-- Drops links older than p_ttl, then all but the newest p_per_host of each host.
CREATE FUNCTION tracks.prune_live_links(p_ttl INTERVAL, p_per_host INTEGER) RETURNS BIGINT
LANGUAGE plpgsql AS $$
DECLARE
    n BIGINT;
    m BIGINT;
BEGIN
    DELETE FROM tracks.live_link WHERE seen_at < now() - p_ttl;
    GET DIAGNOSTICS n = ROW_COUNT;
    DELETE FROM tracks.live_link l USING (
        SELECT id, row_number() OVER (PARTITION BY host ORDER BY seen_at DESC, id DESC) AS r FROM tracks.live_link
    ) x WHERE x.id = l.id AND x.r > p_per_host;
    GET DIAGNOSTICS m = ROW_COUNT;
    RETURN n + m;
END;
$$;
