-- lint: new-table
-- Walks: tracks-walker follows each running ad's saved link to its landing
-- page, and one step further (the page its main button leads to), the way the
-- collector's funnel walker did (internal/funnel at e20148c). Every walk is
-- written whole to a raw file first (walk/<yyyy>/…, archived like capture's
-- files and listed in walk_file); the tables below are what parsing it gave,
-- and tracks-walker replay rebuilds them from the raw files for any range.

-- Raw walk files in the archive: one minute of one walker instance.
CREATE TABLE tracks.walk_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,          -- walk/<yyyy>/<mm>/<dd>/<hh>/capture-<instance>-<hhmm>[-n].ndjson.zst
    minute TIMESTAMPTZ NOT NULL,
    rows INTEGER NOT NULL,
    bytes BIGINT NOT NULL,
    sha256 TEXT NOT NULL,
    archived_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX walk_file_minute_idx ON tracks.walk_file (minute);

-- One walk: an ad's saved link followed from the publisher's page.
CREATE TABLE tracks.walk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id TEXT NOT NULL UNIQUE,    -- the raw record's ULID, so a replay replaces its rows
    at TIMESTAMPTZ NOT NULL,
    ad_id INTEGER NOT NULL,
    creative_id INTEGER NOT NULL,
    account_id INTEGER,
    link_id INTEGER NOT NULL,
    publisher_id INTEGER,
    line TEXT,                         -- proxy line key
    outcome TEXT NOT NULL CHECK (outcome IN ('ok', 'http_error', 'error')),
    error TEXT,
    ms INTEGER NOT NULL
);
CREATE INDEX walk_at_idx ON tracks.walk (at);
CREATE INDEX walk_ad_idx ON tracks.walk (ad_id, at);

-- What a page said, once per distinct content (the collector's landing page
-- version): the hash is over what is kept here, so pages that differ only in
-- a timestamp or a nonce share one row.
CREATE TABLE tracks.page_version (
    hash UUID PRIMARY KEY,
    title TEXT,
    word_count INTEGER NOT NULL,
    headings JSONB NOT NULL DEFAULT '{}'::jsonb,     -- {"h1": [...], "h2": [...]}
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,         -- og:*, twitter:*, description, keywords, author
    favicon_url TEXT,
    pixels JSONB NOT NULL DEFAULT '{}'::jsonb,       -- {"facebook": ["123…"], "google": ["AW-…"], "redtrack": []}
    emails TEXT[] NOT NULL DEFAULT '{}',
    phones TEXT[] NOT NULL DEFAULT '{}',
    companies TEXT[] NOT NULL DEFAULT '{}',          -- "Acme Health LLC" from the page's text
    disclaimers TEXT[] NOT NULL DEFAULT '{}',
    vsl JSONB NOT NULL DEFAULT '{}'::jsonb,
    text TEXT NOT NULL DEFAULT '',                   -- visible text, at most 20,000 characters
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL
);

-- Each page of a walk: step 0 is the landing page, step 1 the page its
-- main button led to.
CREATE TABLE tracks.walk_page (
    walk_id BIGINT NOT NULL REFERENCES tracks.walk(id) ON DELETE CASCADE,
    step SMALLINT NOT NULL,
    url TEXT NOT NULL,                 -- where the step started: the saved link, or the button's link
    final_url TEXT,
    host TEXT,                         -- final host, lowercase, without www.
    status INTEGER,
    hops SMALLINT NOT NULL DEFAULT 0,  -- redirects followed
    version_hash UUID REFERENCES tracks.page_version(hash),
    page_type TEXT,                    -- CHECKOUT, VSL, ADVERTORIAL, QUIZ_SURVEY, LEAD_MAGNET, DIRECT_LANDER
    checkout_platform TEXT,
    seller_account TEXT,               -- the merchant id on the checkout platform, when the page shows it
    PRIMARY KEY (walk_id, step)
);
CREATE INDEX walk_page_host_idx ON tracks.walk_page (host);

-- When each ad was last walked, and when it may be walked again.
CREATE TABLE tracks.walk_state (
    ad_id INTEGER PRIMARY KEY,
    walked_at TIMESTAMPTZ NOT NULL,
    next_at TIMESTAMPTZ NOT NULL,
    failures SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX walk_state_next_idx ON tracks.walk_state (next_at);

-- Ads to walk now: seen in the last hour with a link, never walked or due
-- again, the newest first. Each with the link and publisher of its newest
-- sighting, and that publisher's page for the referer.
CREATE FUNCTION tracks.walks_due(p_limit INTEGER, p_now TIMESTAMPTZ DEFAULT now())
RETURNS TABLE (ad_id INTEGER, creative_id INTEGER, account_id INTEGER, link_id INTEGER, url TEXT,
               publisher_id INTEGER, referer TEXT, seen_at TIMESTAMPTZ)
LANGUAGE sql STABLE AS $$
    SELECT s.ad_id, s.creative_id, s.account_id, s.link_id, l.sample_url, s.publisher_id,
           CASE WHEN p.domain IS NOT NULL THEN 'https://' || p.domain || '/' END, s.seen_at
    FROM (SELECT DISTINCT ON (x.ad_id) x.ad_id, x.creative_id, x.account_id, x.link_id, x.publisher_id, x.seen_at
          FROM tracks.sighting x
          WHERE x.seen_at > p_now - interval '1 hour' AND x.seen_at <= p_now AND x.link_id IS NOT NULL
          ORDER BY x.ad_id, x.seen_at DESC) s
    JOIN tracks.link l ON l.id = s.link_id
    LEFT JOIN tracks.publisher p ON p.id = s.publisher_id
    LEFT JOIN tracks.walk_state w ON w.ad_id = s.ad_id
    WHERE (w.ad_id IS NULL OR w.next_at <= p_now) AND l.sample_url ~ '^https?://'
    ORDER BY w.ad_id IS NOT NULL, s.seen_at DESC
    LIMIT p_limit
$$;

-- Published: every page walked, with what it said.
CREATE VIEW tracks_api.walk_page_v1 AS
SELECT w.id AS walk_id, w.at, w.ad_id, w.creative_id, w.account_id, w.link_id, w.publisher_id, w.outcome,
       p.step, p.url, p.final_url, p.host, p.status, p.hops, p.page_type, p.checkout_platform, p.seller_account,
       p.version_hash
FROM tracks.walk w
JOIN tracks.walk_page p ON p.walk_id = w.id;

-- Published: each distinct page content.
CREATE VIEW tracks_api.page_version_v1 AS
SELECT hash, title, word_count, headings, meta, favicon_url, pixels, emails, phones, companies, disclaimers,
       vsl, text, first_seen_at, last_seen_at
FROM tracks.page_version;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tracks_api_read') THEN
        GRANT SELECT ON tracks_api.walk_page_v1, tracks_api.page_version_v1 TO tracks_api_read;
    END IF;
    -- tracks-walker's own login: reads what is due, writes only its tables.
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tracks_walker') THEN
        GRANT USAGE ON SCHEMA tracks TO tracks_walker;
        GRANT SELECT ON tracks.sighting, tracks.link, tracks.publisher TO tracks_walker;
        GRANT SELECT, INSERT, UPDATE, DELETE ON tracks.walk, tracks.walk_page, tracks.page_version, tracks.walk_state,
            tracks.walk_file TO tracks_walker;
        GRANT USAGE ON ALL SEQUENCES IN SCHEMA tracks TO tracks_walker;
        GRANT EXECUTE ON FUNCTION tracks.walks_due(INTEGER, TIMESTAMPTZ) TO tracks_walker;
    END IF;
END;
$$;
