-- lint: new-table
-- Walk pages keep each URL once (decision 0025, step 1 of 3: expand). A
-- walk_page row held its two URLs in full, about 800 bytes of its 1.2 KB,
-- and the same landing page links come back walk after walk (648,000
-- landing pages had 65,550 distinct links on 2 Oct 2026). tracks.page_url
-- keeps each URL once and tracks.walk_step points at it; everything else in
-- the row is as it was. Every walk page already saved is copied here, and a
-- trigger copies what a tracks-walker still on the old code writes to
-- walk_page, so nothing is missed between the two deploys. walk_page itself
-- stays until `tracks-loader walks drop` has checked every row against its
-- copy (step 3).

-- Each URL a walk met, once. hash is md5(url): an index on long URLs would
-- not fit a btree page.
CREATE TABLE tracks.page_url (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash UUID NOT NULL UNIQUE,
    url TEXT NOT NULL
);

-- The id of a URL, kept the first time it is met. NULL for NULL.
CREATE FUNCTION tracks.url_id(p_url TEXT) RETURNS BIGINT
LANGUAGE plpgsql AS $$
DECLARE
    v BIGINT;
BEGIN
    IF p_url IS NULL THEN
        RETURN NULL;
    END IF;
    SELECT id INTO v FROM tracks.page_url WHERE hash = md5(p_url)::uuid;
    IF v IS NULL THEN
        INSERT INTO tracks.page_url (hash, url) VALUES (md5(p_url)::uuid, p_url)
        ON CONFLICT (hash) DO NOTHING
        RETURNING id INTO v;
    END IF;
    IF v IS NULL THEN
        -- Another walk kept it a moment ago.
        SELECT id INTO v FROM tracks.page_url WHERE hash = md5(p_url)::uuid;
    END IF;
    RETURN v;
END;
$$;

-- Each page of a walk, as walk_page had it, with its URLs by id: step 0 is
-- the landing page, step 1 the page its main button led to.
CREATE TABLE tracks.walk_step (
    walk_id BIGINT NOT NULL REFERENCES tracks.walk(id) ON DELETE CASCADE,
    step SMALLINT NOT NULL,
    url_id BIGINT NOT NULL REFERENCES tracks.page_url(id),        -- where the step started: the saved link, or the button's link
    final_url_id BIGINT REFERENCES tracks.page_url(id),
    host TEXT,                         -- final host, lowercase, without www.
    status INTEGER,
    hops SMALLINT NOT NULL DEFAULT 0,  -- redirects followed
    version_hash UUID REFERENCES tracks.page_version(hash),
    page_type TEXT,                    -- CHECKOUT, VSL, ADVERTORIAL, QUIZ_SURVEY, LEAD_MAGNET, DIRECT_LANDER
    checkout_platform TEXT,
    seller_account TEXT,               -- the merchant id on the checkout platform, when the page shows it
    PRIMARY KEY (walk_id, step)
);

-- While walk_page is still written (a tracks-walker on the old code), each
-- change to it is made to walk_step too.
CREATE FUNCTION tracks.walk_page_to_step() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        DELETE FROM tracks.walk_step WHERE walk_id = OLD.walk_id AND step = OLD.step;
        RETURN OLD;
    END IF;
    IF TG_OP = 'UPDATE' AND (OLD.walk_id, OLD.step) IS DISTINCT FROM (NEW.walk_id, NEW.step) THEN
        DELETE FROM tracks.walk_step WHERE walk_id = OLD.walk_id AND step = OLD.step;
    END IF;
    INSERT INTO tracks.walk_step (walk_id, step, url_id, final_url_id, host, status, hops, version_hash, page_type,
                                  checkout_platform, seller_account)
    VALUES (NEW.walk_id, NEW.step, tracks.url_id(NEW.url), tracks.url_id(NEW.final_url), NEW.host, NEW.status, NEW.hops,
            NEW.version_hash, NEW.page_type, NEW.checkout_platform, NEW.seller_account)
    ON CONFLICT (walk_id, step) DO UPDATE SET
        url_id = EXCLUDED.url_id, final_url_id = EXCLUDED.final_url_id, host = EXCLUDED.host,
        status = EXCLUDED.status, hops = EXCLUDED.hops, version_hash = EXCLUDED.version_hash,
        page_type = EXCLUDED.page_type, checkout_platform = EXCLUDED.checkout_platform,
        seller_account = EXCLUDED.seller_account;
    RETURN NEW;
END;
$$;

-- The trigger comes before the copy: its lock holds walk_page's writers back
-- until this commits, so no row lands between the copy and the trigger.
CREATE TRIGGER walk_page_to_step AFTER INSERT OR UPDATE OR DELETE ON tracks.walk_page
FOR EACH ROW EXECUTE FUNCTION tracks.walk_page_to_step();

INSERT INTO tracks.page_url (hash, url)
SELECT md5(u)::uuid, u
FROM (SELECT url AS u FROM tracks.walk_page
      UNION
      SELECT final_url FROM tracks.walk_page WHERE final_url IS NOT NULL) x
ON CONFLICT (hash) DO NOTHING;

INSERT INTO tracks.walk_step (walk_id, step, url_id, final_url_id, host, status, hops, version_hash, page_type,
                              checkout_platform, seller_account)
SELECT p.walk_id, p.step, u.id, f.id, p.host, p.status, p.hops, p.version_hash, p.page_type, p.checkout_platform,
       p.seller_account
FROM tracks.walk_page p
JOIN tracks.page_url u ON u.hash = md5(p.url)::uuid
LEFT JOIN tracks.page_url f ON f.hash = md5(p.final_url)::uuid;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'tracks_walker') THEN
        GRANT SELECT, INSERT, UPDATE, DELETE ON tracks.walk_step, tracks.page_url TO tracks_walker;
        GRANT USAGE ON ALL SEQUENCES IN SCHEMA tracks TO tracks_walker;
        GRANT EXECUTE ON FUNCTION tracks.url_id(TEXT) TO tracks_walker;
    END IF;
END;
$$;
