// Package testdb gives a test its own throwaway database with the raposa
// migrations applied. It needs PG_TEST_URL (any database on a server the test
// may create databases on); without it the test is skipped.
package testdb

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"io"
	"log/slog"
	"net/url"
	"os"
	"testing"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/Raposa-Industries/adhunters/kit/migrate"
	"github.com/Raposa-Industries/adhunters/kit/pg"
	"github.com/Raposa-Industries/adhunters/raposa/migrations"
)

// New creates a database, migrates it, and drops it when the test ends.
func New(t testing.TB) *pgxpool.Pool {
	t.Helper()
	base := os.Getenv("PG_TEST_URL")
	if base == "" {
		t.Skip("PG_TEST_URL not set")
	}
	ctx := context.Background()
	admin, err := pgx.Connect(ctx, base)
	if err != nil {
		t.Fatal(err)
	}
	b := make([]byte, 6)
	_, _ = rand.Read(b)
	name := "raposa_test_" + hex.EncodeToString(b)
	if _, err := admin.Exec(ctx, "CREATE DATABASE "+name); err != nil {
		t.Fatal(err)
	}
	u, err := url.Parse(base)
	if err != nil {
		t.Fatal(err)
	}
	u.Path = "/" + name
	q := u.Query()
	q.Set("timezone", "UTC")
	u.RawQuery = q.Encode()
	pool, err := pg.Open(ctx, pg.Config{URL: u.String(), AppName: "raposa-test", StatementTimeout: time.Minute, MaxConns: 8})
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		pool.Close()
		_, _ = admin.Exec(ctx, "DROP DATABASE IF EXISTS "+name+" WITH (FORCE)")
		_ = admin.Close(ctx)
	})
	migs, err := migrations.Load()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := migrate.Up(ctx, pool, slog.New(slog.NewTextHandler(io.Discard, nil)), migrations.Schema, migs); err != nil {
		t.Fatal(err)
	}
	return pool
}

// Tracks creates a stand-in for the Tracks views Raposa reads
// (contract/sql/tracks), as plain tables a test fills, and
// take_live_link_v1 over them. Raposa's code may only read what is here.
func Tracks(t testing.TB, pool *pgxpool.Pool) {
	t.Helper()
	if _, err := pool.Exec(context.Background(), tracksFixture); err != nil {
		t.Fatal(err)
	}
}

const tracksFixture = `
CREATE SCHEMA tracks_api;
CREATE TABLE tracks_api.device_v1 (id SMALLINT PRIMARY KEY, code TEXT NOT NULL);
INSERT INTO tracks_api.device_v1 VALUES (1, 'desktop'), (2, 'phone');
CREATE TABLE tracks_api.publisher_v1 (id INTEGER PRIMARY KEY, network_id SMALLINT, name TEXT NOT NULL, domain TEXT,
    first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.campaign_v1 (id INTEGER PRIMARY KEY, network_id SMALLINT, external_id TEXT NOT NULL, name TEXT,
    account_id INTEGER, parent_external_id TEXT, parent_name TEXT, objective TEXT,
    first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.ad_v1 (id INTEGER PRIMARY KEY, creative_id INTEGER NOT NULL, headline TEXT, description TEXT,
    cta TEXT, brand_id INTEGER, account_id INTEGER, first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.link_v1 (id INTEGER PRIMARY KEY, link_key UUID, host TEXT NOT NULL, path TEXT, item_id TEXT,
    tracker TEXT, affiliate_network TEXT, params JSONB, sample_url TEXT, first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.ad_daily_v1 (day DATE, ad_id INTEGER, publisher_id INTEGER, device_id SMALLINT, creative_id INTEGER,
    sightings INTEGER, scrapes INTEGER, feed_position_sum BIGINT, first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.creative_link_daily_v1 (day DATE, creative_id INTEGER, link_id INTEGER, sightings INTEGER,
    first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.creative_campaign_daily_v1 (day DATE, creative_id INTEGER, campaign_id INTEGER, sightings INTEGER,
    first_seen_at TIMESTAMPTZ, last_seen_at TIMESTAMPTZ);
CREATE TABLE tracks_api.sighting_v1 (seen_at TIMESTAMPTZ, scrape_id BIGINT, ad_id INTEGER, creative_id INTEGER,
    publisher_id INTEGER, device_id SMALLINT, placement_id INTEGER, campaign_id INTEGER, link_id INTEGER, account_id INTEGER,
    brand_id INTEGER, site_id INTEGER, ecpa_percentile SMALLINT, feed_position SMALLINT, block_position SMALLINT,
    bid_price NUMERIC, second_price NUMERIC);
CREATE TABLE tracks_api.live_link_v1 (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, host TEXT, url TEXT,
    network TEXT, campaign_external_id TEXT, device TEXT, publisher TEXT, page_url TEXT, ad_id INTEGER, creative_id INTEGER,
    seen_at TIMESTAMPTZ, taken_at TIMESTAMPTZ);
CREATE FUNCTION tracks_api.take_live_link_v1(p_host TEXT, p_campaign TEXT, p_device TEXT, p_any_device BOOLEAN)
RETURNS TABLE (url TEXT, campaign_external_id TEXT, device TEXT, publisher TEXT, page_url TEXT, seen_at TIMESTAMPTZ)
LANGUAGE sql AS $$
    UPDATE tracks_api.live_link_v1 l SET taken_at = now()
    WHERE l.id = (
        SELECT c.id FROM tracks_api.live_link_v1 c
        WHERE c.host = regexp_replace(regexp_replace(lower(btrim(p_host)), '^www\.', ''), '^secure\.', '')
          AND c.taken_at IS NULL
          AND c.seen_at > now() - interval '15 minutes'
          AND (COALESCE(p_campaign, '') = '' OR COALESCE(c.campaign_external_id, '') IN ('', p_campaign))
          AND (c.device = p_device OR p_any_device)
        ORDER BY (c.device = p_device) DESC, c.seen_at DESC, c.id DESC
        LIMIT 1
        FOR UPDATE SKIP LOCKED
    )
    RETURNING l.url, l.campaign_external_id, l.device, l.publisher, l.page_url, l.seen_at
$$;
`
