-- lint: new-table
-- Spy's settings, and the two groupings its numbers are cut by: which
-- operator each account belongs to, and which vertical each creative is in.
-- Ported from the collector's spy schema at e20148c (013, 016, 023, 025, 026,
-- 027, 030, 033). Every id that names an ad, creative, account, publisher or
-- device is Tracks' id (tracks_api); operator ids are Spy's own.
--
-- The grouping itself (operators from sites, clues and account names; the
-- vertical classifier) needs the landing pages Tracks does not collect yet.
-- Until it moves here, spy-numbers import-old copies both groupings from the
-- collector's database, as often as it is run.

-- Tunables. Change a value here, no deploy needed: every refresh reads them.
CREATE TABLE spy.setting (
    name TEXT PRIMARY KEY,
    value NUMERIC,
    text_value TEXT,
    note TEXT NOT NULL,
    CHECK (value IS NOT NULL OR text_value IS NOT NULL)
);

INSERT INTO spy.setting (name, value, text_value, note) VALUES
    ('window_hours', 2, NULL, 'Direction: hours judged, the current hour so far plus the hours before it.'),
    ('usual_weeks', 3, NULL, 'Direction: weeks back for the usual value (the same hour and weekday).'),
    ('usual_publisher_days', 21, NULL, 'Direction: days back that decide where an ad usually runs.'),
    ('member_days', 28, NULL, 'Direction: ads seen in these days are followed.'),
    ('min_expected', 5, NULL, 'Direction is judged only when the usual value expects this many sightings in the window, or this many were seen.'),
    ('min_z', 2, NULL, 'Rising and fading need the gap to the usual value to be this many square roots of the expected count.'),
    ('rise_enter', 1.5, NULL, 'Per-scrape ratio to usual that makes rising.'),
    ('rise_exit', 1.25, NULL, 'Rising stays rising until the ratio falls below this.'),
    ('fade_enter', 0.6, NULL, 'Per-scrape ratio to usual that makes fading.'),
    ('fade_exit', 0.75, NULL, 'Fading stays fading until the ratio climbs above this.'),
    ('flat_low', 0.8, NULL, 'Ratios between flat_low and flat_high count as flat.'),
    ('flat_high', 1.25, NULL, 'Ratios between flat_low and flat_high count as flat.'),
    ('free_rise_rest_max', 0.8, NULL, 'Free rise: the rest of the vertical per scrape is at or below this ratio to usual.'),
    ('stopped_hours', 6, NULL, 'Not seen for this many hours can mean stopped.'),
    ('stopped_min_expected', 3, NULL, 'Stopped only when the usual value expected at least this many sightings in those hours.'),
    ('scaled_cum_share_pct', 50, NULL, 'Scaled: among the biggest that together make this share of the vertical (7 days).'),
    ('scaled_max_rank', 20, NULL, 'Scaled: rank in the vertical (7 days) at most this.'),
    ('scaled_min_sightings_7d', 100, NULL, 'Scaled: at least this many sightings in 7 days.'),
    ('push_hours', 24, NULL, 'Push signs: new headlines and creatives in the same campaign within these hours.'),
    ('bid_rise', 1.2, NULL, 'Push sign: NewsBreak bid in the window at least this ratio to the 24 hours before.'),
    ('time_zone', NULL, 'America/Sao_Paulo',
     'Time zone of the hours and weekdays in the sentences people read, like "Thu 14h". The client is in São Paulo. A name from the IANA list.');

-- Every setting as one JSON object, numbers as numbers.
CREATE FUNCTION spy.cfg() RETURNS JSONB LANGUAGE sql STABLE
AS $$
    SELECT COALESCE(jsonb_object_agg(name, COALESCE(to_jsonb(value), to_jsonb(text_value))), '{}'::jsonb)
    FROM spy.setting
$$;

-- The time zone setting, or 'UTC' when it is empty or not a known name.
CREATE FUNCTION spy.time_zone() RETURNS TEXT LANGUAGE plpgsql STABLE
AS $$
DECLARE
    tz TEXT;
BEGIN
    SELECT NULLIF(btrim(text_value), '') INTO tz FROM spy.setting WHERE name = 'time_zone';
    IF tz IS NULL THEN
        RETURN 'UTC';
    END IF;
    PERFORM now() AT TIME ZONE tz;
    RETURN tz;
EXCEPTION WHEN invalid_parameter_value THEN
    RETURN 'UTC';
END;
$$;

-- The hours judged, as people read them: "Thu 14h" for one hour, "Thu 13–14h"
-- for more. In the time zone setting. "UTC" is added only when that is UTC.
CREATE FUNCTION spy.slot(p_from TIMESTAMPTZ, p_to TIMESTAMPTZ) RETURNS TEXT LANGUAGE plpgsql STABLE
AS $$
DECLARE
    tz TEXT := spy.time_zone();
BEGIN
    RETURN CASE WHEN p_from = p_to
                THEN to_char(p_to AT TIME ZONE tz, 'Dy HH24"h"')
                ELSE to_char(p_from AT TIME ZONE tz, 'Dy HH24') || '–' || to_char(p_to AT TIME ZONE tz, 'HH24"h"')
           END
           || CASE WHEN tz = 'UTC' THEN ' UTC' ELSE '' END;
END;
$$;

-- Operators: the businesses behind the accounts. The id is kept from the
-- collector, so a code like OP123 means the same operator everywhere.
CREATE TABLE spy.operator (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT GENERATED ALWAYS AS ('OP' || id::text) STORED,
    name TEXT NOT NULL,          -- display name · seller · code
    display_name TEXT,           -- typed by hand, else the oldest running account
    kind TEXT NOT NULL DEFAULT 'direct' CHECK (kind IN ('direct', 'affiliate', 'arbitrage')),
    vertical TEXT,               -- the old market label, when there was one
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Which operator each Tracks account belongs to. An account with no row is
-- not grouped yet, and its sightings count for no operator.
CREATE TABLE spy.account_operator (
    account_id INTEGER PRIMARY KEY,
    operator_id INTEGER NOT NULL REFERENCES spy.operator(id) ON DELETE CASCADE
);
CREATE INDEX account_operator_operator_idx ON spy.account_operator (operator_id);

-- The vertical of each Tracks creative. No row: not classified yet.
CREATE TABLE spy.creative_vertical (
    creative_id INTEGER PRIMARY KEY,
    vertical TEXT,               -- the broad one: health, finance, ... Direction's market
    subvertical TEXT,            -- best guess, also when unsure
    shown_vertical TEXT,         -- what the lists show: a health subvertical's group, any other its own name
    confidence NUMERIC(3, 2) NOT NULL DEFAULT 0,
    unsure BOOLEAN NOT NULL DEFAULT TRUE,  -- below 0.6
    source TEXT,                 -- headline, landing_page, funnel_step, seller, model
    health_from_funnel BOOLEAN NOT NULL DEFAULT FALSE
);

-- When each grouping was last copied, and how much of it.
CREATE TABLE spy.import_mark (
    what TEXT PRIMARY KEY,
    done_at TIMESTAMPTZ NOT NULL,
    copied INTEGER NOT NULL,
    skipped INTEGER NOT NULL     -- rows whose account or creative Tracks has not seen yet
);
