-- lint: new-table
-- Raposa's tunables and its ladder of disguises, as the collector had them
-- at e20148c (migrations 028, 031, 035, 037 and 041), in schema raposa.
-- Changing a value here needs no deploy: the engine reads both on every visit.

CREATE TABLE raposa.setting (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    note TEXT NOT NULL DEFAULT ''
);

INSERT INTO raposa.setting (key, value, note) VALUES
    ('visits_target', '100',
     'Visits per deep investigation once a rung breaks through, to measure the variant shares.'),
    ('visits_window_minutes', '120',
     'The sample visits are spread over this many minutes, so the operator sees a normal trickle.'),
    ('ladder_tries_per_rung', '2',
     'How many visits one rung gets before the ladder moves up.'),
    ('avoid_places', 'New York,New York City,Brooklyn,Queens,Manhattan,Los Angeles,Chicago,San Francisco,Austin,Atlanta,Boston,Seattle,Denver,Miami,Dallas,Bellevue,Redmond,Mountain View,Menlo Park,Ashburn',
     'Cities an operator watches, because an ad network has an office there. Never used for a dark page visit.'),
    ('avoid_regions', '',
     'States avoided as well. Empty by default: the cities above are enough.'),
    ('sample_states', 'Ohio,Iowa,Indiana,Missouri,Kentucky,Tennessee,Alabama,Oklahoma,Kansas,Nebraska,Arkansas,Mississippi,South Carolina,West Virginia,Maine,Idaho,Montana,Wyoming,New Mexico,Utah',
     'States the residential line is pinned to, one per visit, round robin. None holds an ad network office.'),
    ('max_page_bytes', '5242880',
     'HTML larger than this is cut before storing. 5 MB.'),
    ('funnel_max_steps', '6',
     'How far past the first page one sample visit follows the funnel.'),
    ('browser_dwell_ms', '8000',
     'How long the browser stays on a page before reading it.'),
    ('residential_budget_bytes', '209715200',
     'Metered residential traffic one investigation may spend; its sample stops there. 200 MB: ten deep investigations fit in 2 GB.'),
    ('max_active', '10',
     'Investigations started and not finished at once. A deep one holds its place for about 120 minutes.'),
    ('quick_max_running', '6',
     'Quick investigations among max_active, so a deep one someone asked for always finds room.'),
    ('live_link_wait_seconds', '180',
     'How long a visit waits for Tracks to see the ad again when no live link is on hand.'),
    ('retry_limit', '4',
     'Attempts in all for a deep investigation that finds no dark page.'),
    ('retry_pace_minutes', '12',
     'Retries are released this far apart, so the workers are fed evenly instead of a batch at once.'),
    ('retry_min_gap_minutes', '30',
     'A creative is not looked at again within this many minutes of its last attempt.'),
    ('burn_window_days', '7',
     'Days of visits a burned line is judged on. A burned line is tried again after this many days.'),
    ('burn_min_visits', '5',
     'Visits a line, and each line it is compared with, needs on one site and rung.'),
    ('burn_other_dark_pct', '50',
     'Share of dark pages the other lines need for a line with none to count as burned.'),
    ('burn_general_sites', '10',
     'Sites a line must be burned for to be burned in general.');

CREATE TABLE raposa.disguise (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rung SMALLINT NOT NULL UNIQUE,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    -- fetch is a plain HTTP request and costs almost nothing; browser is
    -- headless Chromium through raposa-browser.
    engine TEXT NOT NULL CHECK (engine IN ('fetch', 'browser')),
    line_role TEXT NOT NULL CHECK (line_role IN ('direct', 'dc', 'isp', 'residential')),
    -- campaign: the device the ad runs on; other: the opposite one.
    device_rule TEXT NOT NULL DEFAULT 'campaign' CHECK (device_rule IN ('campaign', 'other', 'desktop', 'phone')),
    -- live: a live link from Tracks, with the ad network's click values.
    -- saved: the link Tracks stored, which has them stripped.
    link_kind TEXT NOT NULL DEFAULT 'live' CHECK (link_kind IN ('live', 'saved')),
    pin_place BOOLEAN NOT NULL DEFAULT FALSE,
    load_assets BOOLEAN NOT NULL DEFAULT FALSE,
    human_dwell BOOLEAN NOT NULL DEFAULT FALSE,
    -- Roughly what one visit costs in metered traffic, in KB. Only the
    -- residential line is metered.
    cost_kb INTEGER NOT NULL DEFAULT 0,
    -- The reviewer baseline: its page is the white page every other rung is
    -- compared with. Never a breakthrough.
    is_baseline BOOLEAN NOT NULL DEFAULT FALSE,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    note TEXT NOT NULL DEFAULT ''
);

-- The ladder after the tests of 25 and 26 Sep 2026.
INSERT INTO raposa.disguise
    (rung, code, name, engine, line_role, device_rule, link_kind, pin_place, load_assets, human_dwell, cost_kb, is_baseline, note) VALUES
    (1, 'reviewer',      'Reviewer baseline (ad network office city, saved link)', 'fetch', 'dc',       'desktop',  'saved', FALSE, FALSE, FALSE, 0,    TRUE,
        'What an ad network reviewer sees: the line exiting in New York City when there is one, else a datacenter line. The white page to compare against.'),
    (2, 'isp-fetch',     'US ISP line, fresh link',                          'fetch',   'isp',         'campaign', 'live',  FALSE, FALSE, FALSE, 0,    FALSE,
        'Free. Broke through on heliopulse.site.'),
    (3, 'isp-browser',   'US ISP line, real browser',                        'browser', 'isp',         'campaign', 'live',  FALSE, FALSE, FALSE, 0,    FALSE,
        'Free. For cloakers that need JavaScript to run.'),
    (4, 'res-fetch',     'US home line, fresh link',                         'fetch',   'residential', 'campaign', 'live',  TRUE,  FALSE, FALSE, 60,   FALSE,
        'Metered but cheap. Broke through on the nourishlifeclub family.'),
    (5, 'res-browser',   'US home line, real browser',                       'browser', 'residential', 'campaign', 'live',  TRUE,  FALSE, FALSE, 900,  FALSE,
        'Metered. Runs the page scripts from a home address.'),
    (6, 'res-other-dev', 'US home line, real browser, other device',         'browser', 'residential', 'other',    'live',  TRUE,  FALSE, FALSE, 900,  FALSE,
        'Some operators only open up to the device the campaign does not target.'),
    (7, 'res-full',      'US home line, real browser, everything loaded',    'browser', 'residential', 'campaign', 'live',  TRUE,  TRUE,  FALSE, 2500, FALSE,
        'Images, fonts and video load, so a cloaker counting requests sees a real reader.'),
    (8, 'res-human',     'US home line, real browser, reads like a person',  'browser', 'residential', 'campaign', 'live',  TRUE,  TRUE,  TRUE,  3000, FALSE,
        'Waits, scrolls and moves the mouse before the page decides. The most costly rung.');
