-- lint: new-table
-- Captures: one row per version of one page, and the files each version
-- loads. As the collector's spy.raposa_page, raposa_asset and
-- raposa_page_asset after its migrations 028, 029 and 038, with one change:
-- no file sits in the database. Every kept file is in object storage under
-- its md5, and the database keeps the key, the size and the type.

CREATE TABLE raposa.page (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- md5 of the normalised HTML. The same HTML is the same row.
    content_hash UUID NOT NULL UNIQUE,
    -- The page this version belongs to: host in lower case plus the path
    -- without its trailing slash (pagever.Key).
    page_key TEXT NOT NULL,
    -- sha256 of the normalised words (pagever.TextDigest). New words make a
    -- new version; a new click id in the HTML does not.
    text_digest TEXT NOT NULL,
    url TEXT NOT NULL,
    host TEXT NOT NULL,
    path TEXT NOT NULL,
    title TEXT,
    -- advertorial, vsl, checkout, quiz, article, error, unknown
    page_kind TEXT,
    word_count INTEGER NOT NULL DEFAULT 0,
    html TEXT,
    body_text TEXT,
    html_bytes INTEGER NOT NULL DEFAULT 0,
    headings JSONB NOT NULL DEFAULT '{}'::jsonb,
    meta_tags JSONB NOT NULL DEFAULT '{}'::jsonb,
    pixels JSONB NOT NULL DEFAULT '{}'::jsonb,
    checkout_platform TEXT,
    checkout_merchant_id TEXT,
    outbound_links JSONB NOT NULL DEFAULT '[]'::jsonb,
    -- Set once a visit that reached it saw a dark page.
    is_dark BOOLEAN NOT NULL DEFAULT FALSE,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    times_seen INTEGER NOT NULL DEFAULT 1,

    -- The keeper opens every version once in a real browser and keeps it
    -- whole. html: only the HTML a visit saw, and nothing more is wanted.
    -- queued: waits for the keeper. capturing: the keeper has it until
    -- capture_claimed_until. complete: every file kept. failed: three
    -- attempts, capture_note says why.
    capture_state TEXT NOT NULL DEFAULT 'html'
        CHECK (capture_state IN ('html', 'queued', 'capturing', 'complete', 'failed')),
    capture_note TEXT,
    capture_attempts SMALLINT NOT NULL DEFAULT 0,
    capture_claimed_until TIMESTAMPTZ,
    captured_at TIMESTAMPTZ,
    -- The page as the browser left it after its scripts ran.
    rendered_html TEXT,
    capture_line TEXT,
    capture_bytes BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX page_key_idx ON raposa.page (page_key, id DESC);
CREATE INDEX page_queued_idx ON raposa.page (id) WHERE capture_state IN ('queued', 'capturing');

CREATE TABLE raposa.asset (
    -- md5 of the bytes; of the address when there are no bytes.
    content_hash UUID PRIMARY KEY,
    media_type TEXT NOT NULL DEFAULT 'application/octet-stream',
    size_bytes BIGINT NOT NULL DEFAULT 0 CHECK (size_bytes >= 0),
    -- Where the bytes are in object storage. NULL when they were not kept,
    -- and skipped_reason says why.
    object_key TEXT,
    skipped_reason TEXT,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE raposa.page_asset (
    page_id INTEGER NOT NULL REFERENCES raposa.page (id) ON DELETE CASCADE,
    content_hash UUID NOT NULL REFERENCES raposa.asset (content_hash),
    -- image, video, stylesheet, script, font, other
    role TEXT NOT NULL DEFAULT 'other',
    source_url TEXT NOT NULL
);
-- Keyed on the md5 of the address: an ad network's view link can be longer
-- than a btree row holds (the collector's migration 038).
CREATE UNIQUE INDEX page_asset_key ON raposa.page_asset (page_id, md5(source_url));
CREATE INDEX page_asset_hash_idx ON raposa.page_asset (content_hash);
