-- lint: new-table
-- Investigations, their visits and the variants they found. As the
-- collector's spy.raposa_job, raposa_visit, raposa_step and raposa_variant
-- (migrations 013, 028, 031, 035 and 041), with one change in how the work is
-- held: an investigation is claimed one visit at a time. Between two visits
-- its whole state is in the row (progress), so a restart resumes it at its
-- next visit instead of abandoning it.

CREATE TABLE raposa.investigation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The ad as Tracks knows it (tracks_api.creative_v1, ad_v1). The ad is
    -- optional: without it any headline of the creative will do.
    creative_id INTEGER NOT NULL,
    ad_id INTEGER,
    -- deep: the whole ladder, then visits_target sample visits on the rung
    -- that broke through, retried while it finds no dark page.
    -- quick: only the rungs that cost nothing, the landing page's HTML only,
    -- no sample, no retry.
    mode TEXT NOT NULL CHECK (mode IN ('deep', 'quick')),
    -- user: someone asked for it. auto: queued by Raposa itself. retry: a
    -- deep one that found no dark page, queued again.
    origin TEXT NOT NULL DEFAULT 'user' CHECK (origin IN ('user', 'auto', 'retry')),
    requested_by TEXT NOT NULL DEFAULT '',
    requested_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- waiting: not started. running: started, between or inside visits.
    status TEXT NOT NULL DEFAULT 'waiting'
        CHECK (status IN ('waiting', 'running', 'completed', 'failed', 'stopped')),
    stop_requested BOOLEAN NOT NULL DEFAULT FALSE,

    -- Filled when it starts, from Tracks: the saved link, the publisher page
    -- it ran on, and the site whose burned lines it skips.
    target_click_url TEXT NOT NULL DEFAULT '',
    publisher_referer TEXT NOT NULL DEFAULT '',
    target_device TEXT NOT NULL DEFAULT 'desktop',
    publisher_id INTEGER,
    burn_scope TEXT NOT NULL DEFAULT '',

    -- For the screens: what it is doing now.
    -- queued, baseline, climbing, sampling, done
    stage TEXT NOT NULL DEFAULT 'queued',
    stage_note TEXT NOT NULL DEFAULT '',
    rung_reached SMALLINT NOT NULL DEFAULT 0,
    breach_rung SMALLINT,
    white_page_id INTEGER REFERENCES raposa.page (id),
    visits_target INTEGER NOT NULL DEFAULT 0,
    visits_done INTEGER NOT NULL DEFAULT 0,
    variants_count SMALLINT NOT NULL DEFAULT 0,
    bytes_used BIGINT NOT NULL DEFAULT 0,

    -- The verdict. confidence is the share of visits on the rung that broke
    -- through that saw a dark page, nothing else.
    is_cloaked BOOLEAN NOT NULL DEFAULT FALSE,
    cloaked_confidence NUMERIC(5, 2) NOT NULL DEFAULT 0,
    reviewer_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    raposa_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    checkout_data JSONB NOT NULL DEFAULT '{}'::jsonb,

    -- A chain of attempts: the first investigation of the chain, and which
    -- attempt this is.
    retry_of BIGINT REFERENCES raposa.investigation (id) ON DELETE SET NULL,
    attempt SMALLINT NOT NULL DEFAULT 1,

    -- The work. A worker claims the investigation for one visit when
    -- next_visit_at has come: claim_token and claimed_until say who holds
    -- it. progress is everything the next visit needs to know.
    next_visit_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_by TEXT,
    claim_token UUID,
    claimed_until TIMESTAMPTZ,
    progress JSONB NOT NULL DEFAULT '{}'::jsonb,

    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);
CREATE INDEX investigation_due_idx ON raposa.investigation (next_visit_at) WHERE status IN ('waiting', 'running');
CREATE INDEX investigation_creative_idx ON raposa.investigation (creative_id, requested_at DESC);
CREATE INDEX investigation_requested_idx ON raposa.investigation (requested_at DESC);
CREATE INDEX investigation_scope_idx ON raposa.investigation (burn_scope) WHERE burn_scope <> '';

-- What an investigation did, line by line, for the screens and for anyone
-- reading back why it decided what it did.
CREATE TABLE raposa.log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT NOT NULL REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    at TIMESTAMPTZ NOT NULL DEFAULT now(),
    line TEXT NOT NULL
);
CREATE INDEX log_investigation_idx ON raposa.log (investigation_id, id);

CREATE TABLE raposa.visit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT NOT NULL REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    -- ladder while climbing, sample while measuring the variant shares.
    purpose TEXT NOT NULL CHECK (purpose IN ('ladder', 'sample')),
    rung SMALLINT NOT NULL,
    disguise_id SMALLINT REFERENCES raposa.disguise (id),
    attempt SMALLINT NOT NULL DEFAULT 1,
    line_key TEXT NOT NULL DEFAULT '',
    place TEXT NOT NULL DEFAULT '',
    exit_ip TEXT,
    device TEXT NOT NULL DEFAULT '',
    engine TEXT NOT NULL DEFAULT 'fetch',
    link_kind TEXT NOT NULL DEFAULT 'live',
    -- The link actually used, so a visit can be repeated by hand.
    target_url TEXT NOT NULL DEFAULT '',
    referer TEXT NOT NULL DEFAULT '',
    -- white saw the reviewer page, dark something else, error nothing.
    outcome TEXT NOT NULL CHECK (outcome IN ('white', 'dark', 'error')),
    landed_page_id INTEGER REFERENCES raposa.page (id),
    steps_count SMALLINT NOT NULL DEFAULT 0,
    status_code SMALLINT,
    redirect_hops JSONB NOT NULL DEFAULT '[]'::jsonb,
    bytes_used INTEGER NOT NULL DEFAULT 0,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX visit_investigation_idx ON raposa.visit (investigation_id, started_at);
CREATE INDEX visit_started_idx ON raposa.visit (started_at);

CREATE TABLE raposa.step (
    visit_id BIGINT NOT NULL REFERENCES raposa.visit (id) ON DELETE CASCADE,
    step_no SMALLINT NOT NULL,
    page_id INTEGER NOT NULL REFERENCES raposa.page (id),
    -- landing, redirect, cta
    reached_by TEXT NOT NULL DEFAULT 'cta',
    clicked_text TEXT,
    clicked_url TEXT,
    PRIMARY KEY (visit_id, step_no)
);
CREATE INDEX step_page_idx ON raposa.step (page_id);

-- One distinct dark funnel and its share of the sample visits.
CREATE TABLE raposa.variant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT NOT NULL REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    -- md5 of the content hashes of every step, in order.
    path_hash UUID NOT NULL,
    page_ids INTEGER[] NOT NULL DEFAULT '{}',
    first_page_id INTEGER REFERENCES raposa.page (id),
    label TEXT NOT NULL DEFAULT '',
    visits INTEGER NOT NULL DEFAULT 0,
    share_pct NUMERIC(5, 2) NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (investigation_id, path_hash)
);

-- Recounts the distinct dark funnels of one investigation from its sample
-- visits. The collector's spy.refresh_raposa_variants.
CREATE FUNCTION raposa.refresh_variants(p_id BIGINT) RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    total INTEGER;
BEGIN
    CREATE TEMP TABLE IF NOT EXISTS _raposa_paths (
        visit_id BIGINT, path_hash UUID, page_ids INTEGER[], first_page_id INTEGER
    ) ON COMMIT DROP;
    DELETE FROM _raposa_paths;

    INSERT INTO _raposa_paths (visit_id, path_hash, page_ids, first_page_id)
    SELECT v.id,
           md5(string_agg(p.content_hash::text, '>' ORDER BY s.step_no))::uuid,
           array_agg(s.page_id ORDER BY s.step_no),
           (array_agg(s.page_id ORDER BY s.step_no))[1]
    FROM raposa.visit v
    JOIN raposa.step s ON s.visit_id = v.id
    JOIN raposa.page p ON p.id = s.page_id
    WHERE v.investigation_id = p_id AND v.outcome = 'dark' AND v.purpose = 'sample'
    GROUP BY v.id;

    SELECT count(*) INTO total FROM _raposa_paths;
    IF total = 0 THEN
        UPDATE raposa.investigation SET variants_count = 0 WHERE id = p_id;
        RETURN 0;
    END IF;

    INSERT INTO raposa.variant AS rv (investigation_id, path_hash, page_ids, first_page_id, label, visits, share_pct)
    SELECT p_id, t.path_hash, t.page_ids, t.first_page_id,
           COALESCE(pg.title, pg.host || pg.path, ''),
           count(*)::int,
           round(count(*) * 100.0 / total, 2)
    FROM _raposa_paths t
    LEFT JOIN raposa.page pg ON pg.id = t.first_page_id
    GROUP BY t.path_hash, t.page_ids, t.first_page_id, pg.title, pg.host, pg.path
    ON CONFLICT (investigation_id, path_hash) DO UPDATE SET
        page_ids = EXCLUDED.page_ids,
        first_page_id = EXCLUDED.first_page_id,
        label = EXCLUDED.label,
        visits = EXCLUDED.visits,
        share_pct = EXCLUDED.share_pct,
        last_seen_at = now();

    UPDATE raposa.investigation
    SET variants_count = (SELECT count(*) FROM raposa.variant WHERE investigation_id = p_id)
    WHERE id = p_id;
    RETURN (SELECT count(*) FROM raposa.variant WHERE investigation_id = p_id);
END;
$$;

-- The next time each self-generated queue may release work: a pointer that
-- only moves forward (the collector's migration 041).
CREATE TABLE raposa.schedule (
    kind TEXT PRIMARY KEY,
    next_at TIMESTAMPTZ NOT NULL
);

-- Takes the next slot of kind: at least p_earliest, at least the pointer,
-- and moves the pointer p_pace on. Callers at the same moment get distinct
-- slots; a slot is never in the past.
CREATE FUNCTION raposa.next_slot(p_kind TEXT, p_earliest TIMESTAMPTZ, p_pace INTERVAL) RETURNS TIMESTAMPTZ
LANGUAGE plpgsql AS $$
DECLARE
    v_next TIMESTAMPTZ;
    v_at   TIMESTAMPTZ;
BEGIN
    INSERT INTO raposa.schedule (kind, next_at) VALUES (p_kind, p_earliest) ON CONFLICT (kind) DO NOTHING;
    SELECT next_at INTO v_next FROM raposa.schedule WHERE kind = p_kind FOR UPDATE;
    v_at := GREATEST(v_next, p_earliest, now());
    UPDATE raposa.schedule SET next_at = v_at + p_pace WHERE kind = p_kind;
    RETURN v_at;
END;
$$;

CREATE FUNCTION raposa.setting_int(p_key TEXT, p_default INTEGER) RETURNS INTEGER
LANGUAGE sql STABLE AS $$
    SELECT COALESCE((SELECT CASE WHEN value ~ '^\s*[0-9]+\s*$' THEN btrim(value)::int END
                     FROM raposa.setting WHERE key = p_key), p_default)
$$;

-- Queues a deep investigation again when it found no dark page and fewer
-- than retry_limit attempts were made, on the paced queue: at least
-- retry_min_gap_minutes after this attempt, retry_pace_minutes after the last
-- retry. A creative with another investigation waiting or running gets none.
-- Returns the new investigation's id, or NULL. The collector's ScheduleRetry.
CREATE FUNCTION raposa.schedule_retry(p_id BIGINT) RETURNS BIGINT
LANGUAGE plpgsql AS $$
DECLARE
    v_lim  INTEGER := raposa.setting_int('retry_limit', 4);
    v_gap  INTEGER := raposa.setting_int('retry_min_gap_minutes', 30);
    v_pace INTEGER := raposa.setting_int('retry_pace_minutes', 12);
    j      raposa.investigation;
    v_at   TIMESTAMPTZ;
    v_new  BIGINT;
BEGIN
    SELECT * INTO j FROM raposa.investigation WHERE id = p_id;
    IF NOT FOUND OR j.mode <> 'deep' OR j.status NOT IN ('completed', 'failed')
       OR j.is_cloaked OR j.breach_rung IS NOT NULL OR j.attempt >= v_lim
       OR EXISTS (SELECT 1 FROM raposa.investigation o
                  WHERE o.creative_id = j.creative_id AND o.id <> j.id AND o.status IN ('waiting', 'running')) THEN
        RETURN NULL;
    END IF;
    v_at := raposa.next_slot('retry', now() + make_interval(mins => v_gap), make_interval(mins => v_pace));
    INSERT INTO raposa.investigation (creative_id, ad_id, mode, origin, requested_by, visits_target,
                                      retry_of, attempt, next_visit_at, stage_note)
    VALUES (j.creative_id, j.ad_id, 'deep', 'retry', j.requested_by, j.visits_target,
            COALESCE(j.retry_of, j.id), j.attempt + 1, v_at,
            format('attempt %s of %s, released by the paced queue for %s UTC: attempt %s got no dark page',
                   j.attempt + 1, v_lim, to_char(v_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI'), j.attempt))
    RETURNING id INTO v_new;
    RETURN v_new;
END;
$$;
