-- lint: new-table
-- Burned lines. As the collector's migration 037, with one change: a burn
-- is kept per site (investigation.burn_scope, 'site:' and the registrable
-- domain of the ad's landing host) instead of per operator, because Raposa
-- cannot read who runs a site until Spy publishes it. When it does, the
-- scope becomes 'operator:<id>' and nothing else here changes.
--
-- An operator can learn a proxy line and show it the white page from then
-- on: on 2026-09-27 isp-6 saw 0 dark pages in 37 visits to one operator
-- while isp-8 and isp-9 saw 37 of 37.
--
-- A line is burned for a site when, on the same rung in the last
-- burn_window_days, it made burn_min_visits or more visits that loaded a page
-- and saw no dark page, while the other lines of that rung that made
-- burn_min_visits or more visits saw a dark page on burn_other_dark_pct of
-- theirs or more. Comparing lines on one site keeps a site that shows
-- everyone the white page from burning every line. A line burned for
-- burn_general_sites sites or more is burned in general.
--
-- Raposa skips a burned line on every rung past the reviewer baseline. A
-- skipped line makes no visits there, so its evidence ages out of the
-- window and it is tried again after burn_window_days.

CREATE TABLE raposa.line_burn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope TEXT NOT NULL,
    line_key TEXT NOT NULL,
    -- The rung the comparison was made on.
    rung SMALLINT NOT NULL,
    -- This line's visits that loaded a page, and its dark ones (0 while
    -- burned); the other lines' on the same rung.
    visits INTEGER NOT NULL,
    dark INTEGER NOT NULL,
    other_visits INTEGER NOT NULL,
    other_dark INTEGER NOT NULL,
    detected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    checked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- NULL while it is burned.
    ended_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX line_burn_active_key ON raposa.line_burn (scope, line_key) WHERE ended_at IS NULL;
CREATE INDEX line_burn_line_idx ON raposa.line_burn (line_key, detected_at);

-- Rebuilds the burns from the visits of the window and returns how many are
-- active. Two callers at once: the second does nothing.
CREATE FUNCTION raposa.refresh_line_burns() RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    v_days INTEGER := raposa.setting_int('burn_window_days', 7);
    v_min  INTEGER := raposa.setting_int('burn_min_visits', 5);
    v_pct  INTEGER := raposa.setting_int('burn_other_dark_pct', 50);
    v_rows INTEGER;
BEGIN
    IF NOT pg_try_advisory_xact_lock(hashtext('raposa.refresh_line_burns')) THEN
        RETURN (SELECT count(*) FROM raposa.line_burn WHERE ended_at IS NULL);
    END IF;

    CREATE TEMP TABLE IF NOT EXISTS _raposa_burn_now (
        scope TEXT, line_key TEXT, rung SMALLINT, visits INTEGER, dark INTEGER,
        other_visits INTEGER, other_dark INTEGER) ON COMMIT DROP;
    DELETE FROM _raposa_burn_now;

    INSERT INTO _raposa_burn_now
    WITH v AS (
        SELECT i.burn_scope AS scope, v.rung, v.line_key,
               count(*)::int AS visits, count(*) FILTER (WHERE v.outcome = 'dark')::int AS dark
        FROM raposa.visit v
        JOIN raposa.investigation i ON i.id = v.investigation_id
        JOIN raposa.disguise d ON d.id = v.disguise_id
        WHERE NOT d.is_baseline AND v.line_key <> '' AND v.outcome IN ('white', 'dark')
          AND v.started_at > now() - make_interval(days => v_days)
          AND i.burn_scope <> ''
        GROUP BY 1, 2, 3
    ), cmp AS (
        SELECT a.scope, a.line_key, a.rung, a.visits, a.dark,
               sum(b.visits)::int AS other_visits, sum(b.dark)::int AS other_dark
        FROM v a
        JOIN v b ON b.scope = a.scope AND b.rung = a.rung AND b.line_key <> a.line_key
                AND b.visits >= v_min
        WHERE a.visits >= v_min AND a.dark = 0
        GROUP BY 1, 2, 3, 4, 5
    )
    -- One row per scope and line: the rung with the most visits behind it.
    SELECT DISTINCT ON (scope, line_key) scope, line_key, rung, visits, dark, other_visits, other_dark
    FROM cmp
    WHERE other_dark * 100 >= v_pct * other_visits
    ORDER BY scope, line_key, visits + other_visits DESC;

    UPDATE raposa.line_burn b SET ended_at = now()
    WHERE b.ended_at IS NULL
      AND NOT EXISTS (SELECT 1 FROM _raposa_burn_now n WHERE n.scope = b.scope AND n.line_key = b.line_key);

    UPDATE raposa.line_burn b
    SET rung = n.rung, visits = n.visits, dark = n.dark, other_visits = n.other_visits,
        other_dark = n.other_dark, checked_at = now()
    FROM _raposa_burn_now n
    WHERE b.ended_at IS NULL AND n.scope = b.scope AND n.line_key = b.line_key;

    INSERT INTO raposa.line_burn (scope, line_key, rung, visits, dark, other_visits, other_dark)
    SELECT n.scope, n.line_key, n.rung, n.visits, n.dark, n.other_visits, n.other_dark
    FROM _raposa_burn_now n
    WHERE NOT EXISTS (SELECT 1 FROM raposa.line_burn b
                      WHERE b.ended_at IS NULL AND b.scope = n.scope AND b.line_key = n.line_key);

    SELECT count(*) INTO v_rows FROM raposa.line_burn WHERE ended_at IS NULL;
    RETURN v_rows;
END;
$$;

-- Per line: how many sites it is burned for now, and whether that makes it
-- burned in general.
CREATE VIEW raposa.line_status AS
SELECT b.line_key,
       count(*)::int AS sites_burned,
       count(*) >= raposa.setting_int('burn_general_sites', 10) AS burned_in_general
FROM raposa.line_burn b
WHERE b.ended_at IS NULL
GROUP BY b.line_key;
