-- lint: new-table
-- Evidence and watches.
--
-- Evidence: the landing page a visit reached, and the funnel behind it, as
-- proof of who runs the ad. The collector wrote it into Spy's landing page
-- visits (its migration 035); here Raposa keeps it in its own table and
-- publishes it (raposa_api.evidence_v1), and Spy reads it from there. A dark
-- page is evidence: only the operator serves it. A white page is evidence
-- only on the domain the ad's link points to, because a cloaker may send a
-- reviewer to somebody else's site. Each distinct landing page is stored
-- once per investigation, so a deep sample does not count a hundred times.
--
-- Watches: someone follows an investigation, or every investigation of a
-- creative, and hears about it on their phone through Pushcut. The engine
-- writes an event for each thing worth hearing about in the same
-- transaction as the visit that caused it; the notifier delivers each event
-- once to each watch that wants it.

CREATE TABLE raposa.evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT NOT NULL REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    creative_id INTEGER NOT NULL,
    ad_id INTEGER,
    -- The Tracks account that paid for the click (tracks_api.account_v1), when
    -- the campaign the link came from is known.
    account_id INTEGER,
    campaign_external_id TEXT NOT NULL DEFAULT '',
    device TEXT NOT NULL DEFAULT '',
    -- white or dark: what the visit that reached it saw.
    outcome TEXT NOT NULL CHECK (outcome IN ('white', 'dark')),
    landing_page_id INTEGER NOT NULL REFERENCES raposa.page (id),
    final_url TEXT NOT NULL,
    domain TEXT NOT NULL DEFAULT '',
    redirect_hops JSONB NOT NULL DEFAULT '[]'::jsonb,
    page_kind TEXT NOT NULL DEFAULT 'unknown',
    title TEXT NOT NULL DEFAULT '',
    pixels JSONB NOT NULL DEFAULT '{}'::jsonb,
    checkout_platform TEXT NOT NULL DEFAULT '',
    checkout_merchant_id TEXT NOT NULL DEFAULT '',
    -- The first seller found further down the funnel.
    seller_platform TEXT NOT NULL DEFAULT '',
    seller_account TEXT NOT NULL DEFAULT '',
    -- The pages past the landing page, in order: url, title, page_kind,
    -- clicked_text, checkout_platform, merchant_id.
    funnel_steps JSONB NOT NULL DEFAULT '[]'::jsonb,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (investigation_id, landing_page_id)
);
CREATE INDEX evidence_creative_idx ON raposa.evidence (creative_id, recorded_at DESC);
CREATE INDEX evidence_recorded_idx ON raposa.evidence (recorded_at);

-- Things worth hearing about, in the order they happened.
-- started: the investigation began its first visit.
-- dark_found: a rung broke through.
-- finished: completed, failed or stopped; body says which and why.
CREATE TABLE raposa.event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT NOT NULL REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    kind TEXT NOT NULL CHECK (kind IN ('started', 'dark_found', 'finished')),
    title TEXT NOT NULL,
    body TEXT NOT NULL DEFAULT '',
    at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX event_at_idx ON raposa.event (at);
CREATE INDEX event_investigation_idx ON raposa.event (investigation_id, id);

-- One watch. investigation_id: that investigation and its retries. creative_id: every
-- investigation of that creative, retries included. Neither: every
-- investigation. kinds: the events it wants.
CREATE TABLE raposa.watch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    investigation_id BIGINT REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    creative_id INTEGER,
    kinds TEXT[] NOT NULL DEFAULT ARRAY['started', 'dark_found', 'finished'],
    -- The Pushcut notification it is delivered as: the name of one defined in
    -- the Pushcut app of the person watching.
    pushcut_notification TEXT NOT NULL,
    created_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ
);
CREATE INDEX watch_active_idx ON raposa.watch (investigation_id, creative_id) WHERE ended_at IS NULL;

-- One event sent to one watch. sent: Pushcut took it. failed: three tries
-- were refused, error says why. skipped: no Pushcut key on this box.
CREATE TABLE raposa.delivery (
    event_id BIGINT NOT NULL REFERENCES raposa.event (id) ON DELETE CASCADE,
    watch_id BIGINT NOT NULL REFERENCES raposa.watch (id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK (status IN ('pending', 'sent', 'failed', 'skipped')),
    attempts SMALLINT NOT NULL DEFAULT 0,
    error TEXT,
    next_try_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sent_at TIMESTAMPTZ,
    PRIMARY KEY (event_id, watch_id)
);
CREATE INDEX delivery_pending_idx ON raposa.delivery (next_try_at) WHERE status = 'pending';

-- Fans one event out to the watches that want it, as pending deliveries.
-- Called by the engine in the transaction that writes the event, so no
-- event is written without its deliveries.
CREATE FUNCTION raposa.emit(p_investigation BIGINT, p_kind TEXT, p_title TEXT, p_body TEXT) RETURNS BIGINT
LANGUAGE plpgsql AS $$
DECLARE
    v_event BIGINT;
    v_creative INTEGER;
    v_chain BIGINT;
BEGIN
    INSERT INTO raposa.event (investigation_id, kind, title, body)
    VALUES (p_investigation, p_kind, p_title, p_body)
    RETURNING id INTO v_event;
    SELECT creative_id, retry_of INTO v_creative, v_chain FROM raposa.investigation WHERE id = p_investigation;
    INSERT INTO raposa.delivery (event_id, watch_id, status)
    SELECT v_event, w.id, 'pending'
    FROM raposa.watch w
    WHERE w.ended_at IS NULL
      AND p_kind = ANY (w.kinds)
      AND (w.investigation_id IN (p_investigation, v_chain)
           OR (w.investigation_id IS NULL AND w.creative_id = v_creative)
           OR (w.investigation_id IS NULL AND w.creative_id IS NULL));
    RETURN v_event;
END;
$$;
