-- lint: new-table
-- What the team asked for on WhatsApp (feedback of 2026-10-02):
--
-- - Follow a funnel over days: a follow re-runs one investigation's ad every
--   every_hours for days runs, each a deep investigation that starts at the
--   rung that broke through the first time, so the days can be compared.
-- - Splits per step: each step of the dark funnel (advertorial, VSL,
--   checkout) with the share of sample visits that met each page there.
-- - Video links: the player links (VTurb on converteai.net and the like) a
--   page carries, so a VSL can be watched even when its page will not open.
-- - A quick investigation that could not test the ad tries again, on the
--   rungs that cost nothing.

-- The video player links found in the page's HTML or on the way to it.
ALTER TABLE raposa.page ADD COLUMN video_links TEXT[] NOT NULL DEFAULT '{}';

-- A follow-up run of a followed investigation: which follow, which day.
-- start_rung: the climb starts there instead of at the bottom of the ladder.
ALTER TABLE raposa.investigation
    ADD COLUMN follow_id BIGINT,
    ADD COLUMN follow_day SMALLINT,
    ADD COLUMN start_rung SMALLINT;

CREATE TABLE raposa.follow (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- The investigation followed: its creative, ad, breach rung and sample
    -- size are what every day repeats.
    investigation_id BIGINT NOT NULL REFERENCES raposa.investigation (id) ON DELETE CASCADE,
    creative_id INTEGER NOT NULL,
    days SMALLINT NOT NULL CHECK (days BETWEEN 1 AND 7),
    every_hours SMALLINT NOT NULL DEFAULT 24 CHECK (every_hours BETWEEN 1 AND 168),
    done SMALLINT NOT NULL DEFAULT 0,
    next_at TIMESTAMPTZ NOT NULL,
    created_by TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Set when every day ran, or someone ended it.
    ended_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX follow_open_idx ON raposa.follow (investigation_id) WHERE ended_at IS NULL;
CREATE INDEX follow_due_idx ON raposa.follow (next_at) WHERE ended_at IS NULL;
CREATE INDEX investigation_follow_idx ON raposa.investigation (follow_id, follow_day) WHERE follow_id IS NOT NULL;

INSERT INTO raposa.setting (key, value, note) VALUES
    ('quick_retry_limit', '2',
     'Attempts a quick investigation gets when it could not test the ad (no rung loaded a page). Retries use the rungs that cost nothing, like the first.')
ON CONFLICT (key) DO NOTHING;

-- Queues the follow-up runs that are due and returns how many. A creative
-- with an investigation waiting or running waits for the next call (the
-- engine calls it every 5 minutes). Two callers at once: the second queues
-- nothing.
CREATE FUNCTION raposa.release_follows() RETURNS INTEGER
LANGUAGE plpgsql AS $$
DECLARE
    f      raposa.follow;
    j      raposa.investigation;
    v_rows INTEGER := 0;
BEGIN
    IF NOT pg_try_advisory_xact_lock(hashtext('raposa.release_follows')) THEN
        RETURN 0;
    END IF;
    FOR f IN SELECT * FROM raposa.follow WHERE ended_at IS NULL AND next_at <= now() ORDER BY next_at FOR UPDATE LOOP
        IF EXISTS (SELECT 1 FROM raposa.investigation
                   WHERE creative_id = f.creative_id AND status IN ('waiting', 'running')) THEN
            CONTINUE;
        END IF;
        SELECT * INTO j FROM raposa.investigation WHERE id = f.investigation_id;
        INSERT INTO raposa.investigation (creative_id, ad_id, mode, origin, requested_by, visits_target,
                                          follow_id, follow_day, start_rung, stage_note)
        VALUES (j.creative_id, j.ad_id, 'deep', 'user', f.created_by,
                CASE WHEN j.visits_target > 0 THEN j.visits_target ELSE raposa.setting_int('visits_target', 100) END,
                f.id, f.done + 1, j.breach_rung,
                format('day %s of %s following investigation %s', f.done + 1, f.days, j.id));
        UPDATE raposa.follow
        SET done = done + 1,
            next_at = next_at + make_interval(hours => every_hours),
            ended_at = CASE WHEN done + 1 >= days THEN now() END
        WHERE id = f.id;
        v_rows := v_rows + 1;
    END LOOP;
    RETURN v_rows;
END;
$$;

-- Each step of each investigation's dark funnel: the distinct pages the
-- sample visits met at that step (the same words are the same page), and
-- the share of the visits that reached the step which met each one.
CREATE VIEW raposa.step_split AS
WITH steps AS (
    SELECT v.investigation_id, v.id AS visit_id, s.step_no, p.text_digest, p.id AS page_id,
           p.title, p.page_kind, p.host, p.path
    FROM raposa.visit v
    JOIN raposa.step s ON s.visit_id = v.id
    JOIN raposa.page p ON p.id = s.page_id
    WHERE v.outcome = 'dark' AND v.purpose = 'sample'
), reached AS (
    SELECT investigation_id, step_no, count(DISTINCT visit_id) AS visits
    FROM steps GROUP BY 1, 2
)
SELECT st.investigation_id, st.step_no, st.text_digest,
       min(st.page_id) AS page_id,
       (array_agg(st.title ORDER BY st.page_id))[1] AS title,
       (array_agg(st.page_kind ORDER BY st.page_id))[1] AS page_kind,
       (array_agg(st.host || st.path ORDER BY st.page_id))[1] AS address,
       count(DISTINCT st.visit_id)::int AS visits,
       r.visits::int AS step_visits,
       round(count(DISTINCT st.visit_id) * 100.0 / r.visits, 1) AS share_pct
FROM steps st
JOIN reached r USING (investigation_id, step_no)
GROUP BY st.investigation_id, st.step_no, st.text_digest, r.visits;

-- Queues a deep investigation again when it found no dark page, and a
-- quick one when it could not test the ad, while fewer than retry_limit
-- (quick_retry_limit) attempts were made, on the paced queue: at least
-- retry_min_gap_minutes after this attempt, retry_pace_minutes after the last
-- retry. A creative with another investigation waiting or running gets none.
-- A retry keeps the follow it belongs to. Returns the new investigation's id,
-- or NULL.
CREATE OR REPLACE FUNCTION raposa.schedule_retry(p_id BIGINT) RETURNS BIGINT
LANGUAGE plpgsql AS $$
DECLARE
    v_gap  INTEGER := raposa.setting_int('retry_min_gap_minutes', 30);
    v_pace INTEGER := raposa.setting_int('retry_pace_minutes', 12);
    v_lim  INTEGER;
    j      raposa.investigation;
    v_at   TIMESTAMPTZ;
    v_new  BIGINT;
BEGIN
    SELECT * INTO j FROM raposa.investigation WHERE id = p_id;
    IF NOT FOUND THEN
        RETURN NULL;
    END IF;
    IF j.mode = 'deep' THEN
        v_lim := raposa.setting_int('retry_limit', 4);
        IF j.status NOT IN ('completed', 'failed') OR j.is_cloaked OR j.breach_rung IS NOT NULL THEN
            RETURN NULL;
        END IF;
    ELSE
        -- A quick one tries again only when nothing past the reviewer page
        -- loaded: it did not test the ad. One that tested it and saw only
        -- the white page has its answer.
        v_lim := raposa.setting_int('quick_retry_limit', 2);
        IF j.status <> 'failed' OR j.is_cloaked
           OR EXISTS (SELECT 1 FROM raposa.visit v
                      JOIN raposa.disguise d ON d.id = v.disguise_id AND NOT d.is_baseline
                      WHERE v.investigation_id = j.id AND v.outcome IN ('white', 'dark')) THEN
            RETURN NULL;
        END IF;
    END IF;
    IF j.attempt >= v_lim
       OR EXISTS (SELECT 1 FROM raposa.investigation o
                  WHERE o.creative_id = j.creative_id AND o.id <> j.id AND o.status IN ('waiting', 'running')) THEN
        RETURN NULL;
    END IF;
    v_at := raposa.next_slot('retry', now() + make_interval(mins => v_gap), make_interval(mins => v_pace));
    INSERT INTO raposa.investigation (creative_id, ad_id, mode, origin, requested_by, visits_target,
                                      retry_of, attempt, next_visit_at, follow_id, follow_day, start_rung, stage_note)
    VALUES (j.creative_id, j.ad_id, j.mode, 'retry', j.requested_by, j.visits_target,
            COALESCE(j.retry_of, j.id), j.attempt + 1, v_at, j.follow_id, j.follow_day, j.start_rung,
            format('attempt %s of %s, released by the paced queue for %s UTC: attempt %s %s',
                   j.attempt + 1, v_lim, to_char(v_at AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI'), j.attempt,
                   CASE WHEN j.mode = 'deep' THEN 'got no dark page' ELSE 'could not test the ad' END))
    RETURNING id INTO v_new;
    RETURN v_new;
END;
$$;
