-- The collector's spy tables that tracks-bridge writes, as adhunters-collector
-- e20148c plus 042_walk_queue.sql (platform/switch-over/) leave them:
-- pg_dump --schema-only of those tables, their functions, and the network and
-- device rows. Tests load it into a throwaway database (with pg_trgm).
-- Regenerate it when the collector's schema changes.

--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.account (
    id integer NOT NULL,
    network_id smallint DEFAULT 1 NOT NULL,
    external_id text NOT NULL,
    operator_id integer,
    agency_id integer,
    group_reason text,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    org_external_id text
);


--
-- Name: account_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ad; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.ad (
    id integer NOT NULL,
    creative_id integer NOT NULL,
    headline text NOT NULL,
    description text,
    cta text,
    brand_id integer,
    account_id integer,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: ad_account_brand_hourly; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.ad_account_brand_hourly (
    hour timestamp with time zone NOT NULL,
    ad_id integer NOT NULL,
    account_id integer,
    brand_id integer,
    publisher_id integer NOT NULL,
    device_id smallint NOT NULL,
    sightings integer NOT NULL
);


--
-- Name: TABLE ad_account_brand_hourly; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON TABLE spy.ad_account_brand_hourly IS 'Sightings of one ad in one hour under one account and one brand, per publisher and device (033). Written by the collector with every scrape; hours before 033 filled from the sightings, with brand NULL.';


--
-- Name: ad_account_daily; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.ad_account_daily (
    day date NOT NULL,
    ad_id integer NOT NULL,
    account_id integer,
    brand_id integer,
    publisher_id integer NOT NULL,
    device_id smallint NOT NULL,
    creative_id integer NOT NULL,
    sightings integer NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: TABLE ad_account_daily; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON TABLE spy.ad_account_daily IS 'spy.ad_account_brand_hourly per UTC day, with the first and last sighting (033).';


--
-- Name: ad_daily; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.ad_daily (
    day date NOT NULL,
    ad_id integer NOT NULL,
    publisher_id integer NOT NULL,
    device_id smallint NOT NULL,
    creative_id integer NOT NULL,
    sightings integer NOT NULL,
    scrapes integer NOT NULL,
    feed_position_sum bigint NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: ad_hourly; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.ad_hourly (
    hour timestamp with time zone NOT NULL,
    ad_id integer NOT NULL,
    publisher_id integer NOT NULL,
    device_id smallint NOT NULL,
    feed_position_min smallint,
    feed_position_max smallint,
    sightings integer NOT NULL,
    scrapes integer NOT NULL,
    feed_position_sum bigint NOT NULL
);


--
-- Name: ad_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.ad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.ad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agency; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.agency (
    id integer NOT NULL,
    name_root text NOT NULL,
    name text NOT NULL,
    operator_count integer DEFAULT 0 NOT NULL
);


--
-- Name: agency_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.agency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.agency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: brand; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.brand (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: brand_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaign; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.campaign (
    id integer NOT NULL,
    network_id smallint DEFAULT 1 NOT NULL,
    external_id text NOT NULL,
    name text,
    account_id integer,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL,
    parent_external_id text,
    parent_name text,
    objective text
);


--
-- Name: campaign_daily; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.campaign_daily (
    day date NOT NULL,
    campaign_id integer NOT NULL,
    publisher_id integer NOT NULL,
    sightings integer NOT NULL,
    scrapes integer NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: campaign_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.campaign ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.campaign_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: creative; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.creative (
    id integer NOT NULL,
    uid uuid DEFAULT gen_random_uuid() NOT NULL,
    network_id smallint DEFAULT 1 NOT NULL,
    creative_key text NOT NULL,
    image_url text NOT NULL,
    format_type text,
    video_duration integer,
    thumb_dimensions text,
    language text,
    vertical text,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: creative_campaign; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.creative_campaign (
    creative_id integer NOT NULL,
    campaign_id integer NOT NULL,
    sightings bigint NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: creative_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.creative ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.creative_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: creative_link; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.creative_link (
    creative_id integer NOT NULL,
    link_id integer NOT NULL,
    sightings bigint NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: device; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.device (
    id smallint NOT NULL,
    code text NOT NULL
);


--
-- Name: device_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.device ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.device_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: link; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.link (
    id integer NOT NULL,
    link_key uuid NOT NULL,
    host text NOT NULL,
    path text NOT NULL,
    item_id text,
    tracker text,
    affiliate_network text,
    params jsonb DEFAULT '{}'::jsonb NOT NULL,
    sample_url text NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: link_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.link ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.link_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: network; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.network (
    id smallint NOT NULL,
    code text NOT NULL,
    name text NOT NULL
);


--
-- Name: network_ad; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.network_ad (
    id integer NOT NULL,
    network_id smallint NOT NULL,
    external_id text NOT NULL,
    ad_id integer NOT NULL,
    campaign_id integer,
    creative_external_id text,
    name text,
    started_at timestamp with time zone,
    icon_url text,
    layout text,
    media_aspect text,
    launch_option text,
    iab_tier1 text,
    iab_tier2 text,
    landing_domain text,
    disclaimer text,
    extra jsonb DEFAULT '{}'::jsonb NOT NULL,
    first_seen_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone NOT NULL
);


--
-- Name: TABLE network_ad; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON TABLE spy.network_ad IS 'One ad id on an ad network (NewsBreak adId). Many can share one spy.ad.';


--
-- Name: network_ad_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.network_ad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.network_ad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operator; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.operator (
    id integer NOT NULL,
    uid uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    kind text DEFAULT 'direct'::text NOT NULL,
    name_is_manual boolean DEFAULT false NOT NULL,
    vertical text,
    legacy_market_player_uid uuid,
    site_count integer DEFAULT 0 NOT NULL,
    account_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    code text GENERATED ALWAYS AS (('OP'::text || (id)::text)) STORED,
    display_name text,
    seller_id integer,
    CONSTRAINT operator_kind_check CHECK ((kind = ANY (ARRAY['direct'::text, 'affiliate'::text, 'arbitrage'::text])))
);


--
-- Name: COLUMN operator.name; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON COLUMN spy.operator.name IS 'display_name · seller · code (033).';


--
-- Name: COLUMN operator.name_is_manual; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON COLUMN spy.operator.name_is_manual IS 'display_name was typed by hand; regrouping keeps it (033).';


--
-- Name: COLUMN operator.code; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON COLUMN spy.operator.code IS 'OP and the operator id. Never changes (033).';


--
-- Name: COLUMN operator.display_name; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON COLUMN spy.operator.display_name IS 'Typed by hand when name_is_manual, else the oldest running account (033).';


--
-- Name: COLUMN operator.seller_id; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON COLUMN spy.operator.seller_id IS 'The seller behind most of its checkout pages, ignoring Custom Checkout and Shopify gid (033).';


--
-- Name: operator_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.operator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.operator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: placement; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.placement (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: placement_daily; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.placement_daily (
    day date NOT NULL,
    ad_id integer NOT NULL,
    publisher_id integer NOT NULL,
    placement_id integer NOT NULL,
    sightings integer NOT NULL
);


--
-- Name: placement_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.placement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.placement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proxy_line; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.proxy_line (
    id smallint NOT NULL,
    code text NOT NULL
);


--
-- Name: proxy_line_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.proxy_line ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.proxy_line_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: publisher; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.publisher (
    id integer NOT NULL,
    network_id smallint DEFAULT 1 NOT NULL,
    name text NOT NULL,
    domain text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: publisher_alias; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.publisher_alias (
    alias text NOT NULL,
    publisher_id integer NOT NULL
);


--
-- Name: publisher_hourly; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.publisher_hourly (
    hour timestamp with time zone NOT NULL,
    publisher_id integer NOT NULL,
    device_id smallint NOT NULL,
    scrapes integer NOT NULL,
    sightings integer NOT NULL
);


--
-- Name: publisher_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.publisher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.publisher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scrape; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.scrape (
    id bigint NOT NULL,
    batch_uid uuid,
    scraped_at timestamp with time zone NOT NULL,
    publisher_id integer NOT NULL,
    device_id smallint NOT NULL,
    proxy_line_id smallint,
    ad_count integer NOT NULL,
    latency_ms integer,
    geo_country text,
    trc_route text,
    worker_node text,
    pipeline_version text,
    payload_checksum text
);


--
-- Name: COLUMN scrape.batch_uid; Type: COMMENT; Schema: spy; Owner: -
--

COMMENT ON COLUMN spy.scrape.batch_uid IS 'The collector''s batch id for this scrape (old rows: adhunters_sighting.batch_id or a derived key).';


--
-- Name: scrape_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.scrape ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.scrape_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: seller; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.seller (
    id integer NOT NULL,
    platform text NOT NULL,
    account text NOT NULL
);


--
-- Name: seller_id_seq; Type: SEQUENCE; Schema: spy; Owner: -
--

ALTER TABLE spy.seller ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME spy.seller_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sighting; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.sighting (
    seen_at timestamp with time zone NOT NULL,
    scrape_id bigint NOT NULL,
    ad_id integer NOT NULL,
    creative_id integer NOT NULL,
    publisher_id integer NOT NULL,
    placement_id integer,
    campaign_id integer,
    link_id integer,
    site_id integer,
    ecpa_percentile real,
    device_id smallint NOT NULL,
    feed_position smallint,
    block_position smallint,
    bid_price real,
    second_price real
)
PARTITION BY RANGE (seen_at);


--
-- Name: walk_queue; Type: TABLE; Schema: spy; Owner: -
--

CREATE TABLE spy.walk_queue (
    ad_id integer NOT NULL,
    creative_id integer NOT NULL,
    account_id integer,
    click_url text NOT NULL,
    referer text DEFAULT ''::text NOT NULL,
    queued_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: account account_network_id_external_id_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.account
    ADD CONSTRAINT account_network_id_external_id_key UNIQUE (network_id, external_id);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: ad_account_brand_hourly ad_account_brand_hourly_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad_account_brand_hourly
    ADD CONSTRAINT ad_account_brand_hourly_key UNIQUE NULLS NOT DISTINCT (hour, ad_id, account_id, brand_id, publisher_id, device_id);


--
-- Name: ad_account_daily ad_account_daily_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad_account_daily
    ADD CONSTRAINT ad_account_daily_key UNIQUE NULLS NOT DISTINCT (day, ad_id, account_id, brand_id, publisher_id, device_id);


--
-- Name: ad_daily ad_daily_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad_daily
    ADD CONSTRAINT ad_daily_pkey PRIMARY KEY (day, ad_id, publisher_id, device_id);


--
-- Name: ad_hourly ad_hourly_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad_hourly
    ADD CONSTRAINT ad_hourly_pkey PRIMARY KEY (hour, ad_id, publisher_id, device_id);


--
-- Name: ad ad_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad
    ADD CONSTRAINT ad_pkey PRIMARY KEY (id);


--
-- Name: agency agency_name_root_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.agency
    ADD CONSTRAINT agency_name_root_key UNIQUE (name_root);


--
-- Name: agency agency_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.agency
    ADD CONSTRAINT agency_pkey PRIMARY KEY (id);


--
-- Name: brand brand_name_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.brand
    ADD CONSTRAINT brand_name_key UNIQUE (name);


--
-- Name: brand brand_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.brand
    ADD CONSTRAINT brand_pkey PRIMARY KEY (id);


--
-- Name: campaign_daily campaign_daily_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.campaign_daily
    ADD CONSTRAINT campaign_daily_pkey PRIMARY KEY (day, campaign_id, publisher_id);


--
-- Name: campaign campaign_network_id_external_id_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.campaign
    ADD CONSTRAINT campaign_network_id_external_id_key UNIQUE (network_id, external_id);


--
-- Name: campaign campaign_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.campaign
    ADD CONSTRAINT campaign_pkey PRIMARY KEY (id);


--
-- Name: creative_campaign creative_campaign_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.creative_campaign
    ADD CONSTRAINT creative_campaign_pkey PRIMARY KEY (creative_id, campaign_id);


--
-- Name: creative creative_creative_key_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.creative
    ADD CONSTRAINT creative_creative_key_key UNIQUE (creative_key);


--
-- Name: creative_link creative_link_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.creative_link
    ADD CONSTRAINT creative_link_pkey PRIMARY KEY (creative_id, link_id);


--
-- Name: creative creative_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.creative
    ADD CONSTRAINT creative_pkey PRIMARY KEY (id);


--
-- Name: creative creative_uid_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.creative
    ADD CONSTRAINT creative_uid_key UNIQUE (uid);


--
-- Name: device device_code_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.device
    ADD CONSTRAINT device_code_key UNIQUE (code);


--
-- Name: device device_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.device
    ADD CONSTRAINT device_pkey PRIMARY KEY (id);


--
-- Name: link link_link_key_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.link
    ADD CONSTRAINT link_link_key_key UNIQUE (link_key);


--
-- Name: link link_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.link
    ADD CONSTRAINT link_pkey PRIMARY KEY (id);


--
-- Name: network_ad network_ad_network_id_external_id_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network_ad
    ADD CONSTRAINT network_ad_network_id_external_id_key UNIQUE (network_id, external_id);


--
-- Name: network_ad network_ad_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network_ad
    ADD CONSTRAINT network_ad_pkey PRIMARY KEY (id);


--
-- Name: network network_code_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network
    ADD CONSTRAINT network_code_key UNIQUE (code);


--
-- Name: network network_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network
    ADD CONSTRAINT network_pkey PRIMARY KEY (id);


--
-- Name: operator operator_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.operator
    ADD CONSTRAINT operator_pkey PRIMARY KEY (id);


--
-- Name: operator operator_uid_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.operator
    ADD CONSTRAINT operator_uid_key UNIQUE (uid);


--
-- Name: placement_daily placement_daily_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.placement_daily
    ADD CONSTRAINT placement_daily_pkey PRIMARY KEY (day, ad_id, publisher_id, placement_id);


--
-- Name: placement placement_name_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.placement
    ADD CONSTRAINT placement_name_key UNIQUE (name);


--
-- Name: placement placement_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.placement
    ADD CONSTRAINT placement_pkey PRIMARY KEY (id);


--
-- Name: proxy_line proxy_line_code_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.proxy_line
    ADD CONSTRAINT proxy_line_code_key UNIQUE (code);


--
-- Name: proxy_line proxy_line_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.proxy_line
    ADD CONSTRAINT proxy_line_pkey PRIMARY KEY (id);


--
-- Name: publisher_alias publisher_alias_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.publisher_alias
    ADD CONSTRAINT publisher_alias_pkey PRIMARY KEY (alias);


--
-- Name: publisher_hourly publisher_hourly_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.publisher_hourly
    ADD CONSTRAINT publisher_hourly_pkey PRIMARY KEY (hour, publisher_id, device_id);


--
-- Name: publisher publisher_name_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.publisher
    ADD CONSTRAINT publisher_name_key UNIQUE (name);


--
-- Name: publisher publisher_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.publisher
    ADD CONSTRAINT publisher_pkey PRIMARY KEY (id);


--
-- Name: scrape scrape_legacy_batch_uid_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.scrape
    ADD CONSTRAINT scrape_legacy_batch_uid_key UNIQUE (batch_uid);


--
-- Name: scrape scrape_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.scrape
    ADD CONSTRAINT scrape_pkey PRIMARY KEY (id);


--
-- Name: seller seller_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.seller
    ADD CONSTRAINT seller_pkey PRIMARY KEY (id);


--
-- Name: seller seller_platform_account_key; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.seller
    ADD CONSTRAINT seller_platform_account_key UNIQUE (platform, account);


--
-- Name: walk_queue walk_queue_pkey; Type: CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.walk_queue
    ADD CONSTRAINT walk_queue_pkey PRIMARY KEY (ad_id);


--
-- Name: account_org_idx; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX account_org_idx ON spy.account USING btree (network_id, org_external_id) WHERE (org_external_id IS NOT NULL);


--
-- Name: campaign_parent_idx; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX campaign_parent_idx ON spy.campaign USING btree (network_id, parent_external_id) WHERE (parent_external_id IS NOT NULL);


--
-- Name: idx_spy_account_agency; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_account_agency ON spy.account USING btree (agency_id);


--
-- Name: idx_spy_account_external_id_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_account_external_id_trgm ON spy.account USING gin (external_id public.gin_trgm_ops);


--
-- Name: idx_spy_account_operator; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_account_operator ON spy.account USING btree (operator_id);


--
-- Name: idx_spy_account_org_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_account_org_trgm ON spy.account USING gin (org_external_id public.gin_trgm_ops);


--
-- Name: idx_spy_ad_account; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_account ON spy.ad USING btree (account_id);


--
-- Name: idx_spy_ad_account_brand_hourly_account; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_account_brand_hourly_account ON spy.ad_account_brand_hourly USING btree (account_id, hour);


--
-- Name: idx_spy_ad_account_brand_hourly_ad; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_account_brand_hourly_ad ON spy.ad_account_brand_hourly USING btree (ad_id, hour);


--
-- Name: idx_spy_ad_account_brand_hourly_hour; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_account_brand_hourly_hour ON spy.ad_account_brand_hourly USING btree (hour);


--
-- Name: idx_spy_ad_account_daily_account; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_account_daily_account ON spy.ad_account_daily USING btree (account_id, day);


--
-- Name: idx_spy_ad_account_daily_creative; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_account_daily_creative ON spy.ad_account_daily USING btree (creative_id, day);


--
-- Name: idx_spy_ad_brand; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_brand ON spy.ad USING btree (brand_id);


--
-- Name: idx_spy_ad_brand_account; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_brand_account ON spy.ad USING btree (brand_id, account_id);


--
-- Name: idx_spy_ad_daily_ad; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_daily_ad ON spy.ad_daily USING btree (ad_id, day);


--
-- Name: idx_spy_ad_daily_creative; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_daily_creative ON spy.ad_daily USING btree (creative_id, day);


--
-- Name: idx_spy_ad_description_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_description_trgm ON spy.ad USING gin (description public.gin_trgm_ops);


--
-- Name: idx_spy_ad_headline_lower; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_headline_lower ON spy.ad USING btree ("left"(lower(headline), 200) text_pattern_ops);


--
-- Name: idx_spy_ad_headline_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_headline_trgm ON spy.ad USING gin (headline public.gin_trgm_ops);


--
-- Name: idx_spy_ad_hourly_ad; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_ad_hourly_ad ON spy.ad_hourly USING btree (ad_id, hour);


--
-- Name: idx_spy_brand_name_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_brand_name_trgm ON spy.brand USING gin (name public.gin_trgm_ops);


--
-- Name: idx_spy_campaign_account; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_campaign_account ON spy.campaign USING btree (account_id);


--
-- Name: idx_spy_campaign_daily_campaign; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_campaign_daily_campaign ON spy.campaign_daily USING btree (campaign_id, day);


--
-- Name: idx_spy_creative_campaign_campaign; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_creative_campaign_campaign ON spy.creative_campaign USING btree (campaign_id);


--
-- Name: idx_spy_creative_last_seen; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_creative_last_seen ON spy.creative USING btree (last_seen_at DESC);


--
-- Name: idx_spy_creative_link_link; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_creative_link_link ON spy.creative_link USING btree (link_id);


--
-- Name: idx_spy_link_host; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_link_host ON spy.link USING btree (host);


--
-- Name: idx_spy_operator_name_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_operator_name_trgm ON spy.operator USING gin (name public.gin_trgm_ops);


--
-- Name: idx_spy_placement_daily_ad; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_placement_daily_ad ON spy.placement_daily USING btree (ad_id, day);


--
-- Name: idx_spy_scrape_time; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_scrape_time ON spy.scrape USING btree (scraped_at);


--
-- Name: idx_spy_seller_account_trgm; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_seller_account_trgm ON spy.seller USING gin (account public.gin_trgm_ops);


--
-- Name: idx_spy_sighting_ad; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_sighting_ad ON ONLY spy.sighting USING btree (ad_id, seen_at);


--
-- Name: idx_spy_sighting_seen_brin; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_sighting_seen_brin ON ONLY spy.sighting USING brin (seen_at);


--
-- Name: idx_spy_walk_queue_queued; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX idx_spy_walk_queue_queued ON spy.walk_queue USING btree (queued_at);


--
-- Name: network_ad_ad_idx; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX network_ad_ad_idx ON spy.network_ad USING btree (ad_id);


--
-- Name: network_ad_campaign_idx; Type: INDEX; Schema: spy; Owner: -
--

CREATE INDEX network_ad_campaign_idx ON spy.network_ad USING btree (campaign_id);


--
-- Name: uq_spy_ad; Type: INDEX; Schema: spy; Owner: -
--

CREATE UNIQUE INDEX uq_spy_ad ON spy.ad USING btree (creative_id, md5(headline));


--
-- Name: account account_agency_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.account
    ADD CONSTRAINT account_agency_id_fkey FOREIGN KEY (agency_id) REFERENCES spy.agency(id);


--
-- Name: account account_network_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.account
    ADD CONSTRAINT account_network_id_fkey FOREIGN KEY (network_id) REFERENCES spy.network(id);


--
-- Name: account account_operator_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.account
    ADD CONSTRAINT account_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES spy.operator(id);


--
-- Name: ad ad_account_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad
    ADD CONSTRAINT ad_account_id_fkey FOREIGN KEY (account_id) REFERENCES spy.account(id);


--
-- Name: ad ad_brand_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad
    ADD CONSTRAINT ad_brand_id_fkey FOREIGN KEY (brand_id) REFERENCES spy.brand(id);


--
-- Name: ad ad_creative_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.ad
    ADD CONSTRAINT ad_creative_id_fkey FOREIGN KEY (creative_id) REFERENCES spy.creative(id);


--
-- Name: campaign campaign_account_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.campaign
    ADD CONSTRAINT campaign_account_id_fkey FOREIGN KEY (account_id) REFERENCES spy.account(id);


--
-- Name: campaign campaign_network_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.campaign
    ADD CONSTRAINT campaign_network_id_fkey FOREIGN KEY (network_id) REFERENCES spy.network(id);


--
-- Name: creative creative_network_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.creative
    ADD CONSTRAINT creative_network_id_fkey FOREIGN KEY (network_id) REFERENCES spy.network(id);


--
-- Name: network_ad network_ad_ad_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network_ad
    ADD CONSTRAINT network_ad_ad_id_fkey FOREIGN KEY (ad_id) REFERENCES spy.ad(id);


--
-- Name: network_ad network_ad_campaign_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network_ad
    ADD CONSTRAINT network_ad_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES spy.campaign(id);


--
-- Name: network_ad network_ad_network_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.network_ad
    ADD CONSTRAINT network_ad_network_id_fkey FOREIGN KEY (network_id) REFERENCES spy.network(id);


--
-- Name: publisher_alias publisher_alias_publisher_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.publisher_alias
    ADD CONSTRAINT publisher_alias_publisher_id_fkey FOREIGN KEY (publisher_id) REFERENCES spy.publisher(id);


--
-- Name: publisher publisher_network_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.publisher
    ADD CONSTRAINT publisher_network_id_fkey FOREIGN KEY (network_id) REFERENCES spy.network(id);


--
-- Name: scrape scrape_device_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.scrape
    ADD CONSTRAINT scrape_device_id_fkey FOREIGN KEY (device_id) REFERENCES spy.device(id);


--
-- Name: scrape scrape_proxy_line_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.scrape
    ADD CONSTRAINT scrape_proxy_line_id_fkey FOREIGN KEY (proxy_line_id) REFERENCES spy.proxy_line(id);


--
-- Name: scrape scrape_publisher_id_fkey; Type: FK CONSTRAINT; Schema: spy; Owner: -
--

ALTER TABLE ONLY spy.scrape
    ADD CONSTRAINT scrape_publisher_id_fkey FOREIGN KEY (publisher_id) REFERENCES spy.publisher(id);


--
-- PostgreSQL database dump complete
--


CREATE OR REPLACE FUNCTION spy.ensure_sighting_partitions(p_from date, p_to date)
 RETURNS integer
 LANGUAGE plpgsql
AS $function$
DECLARE
    d DATE := p_from;
    created INTEGER := 0;
    part TEXT;
BEGIN
    WHILE d <= p_to LOOP
        part := 'sighting_' || to_char(d, 'YYYYMMDD');
        IF to_regclass('spy.' || part) IS NULL THEN
            EXECUTE format(
                'CREATE TABLE spy.%I PARTITION OF spy.sighting FOR VALUES FROM (%L) TO (%L)',
                part, d::timestamp AT TIME ZONE 'UTC', (d + 1)::timestamp AT TIME ZONE 'UTC');
            created := created + 1;
        END IF;
        d := d + 1;
    END LOOP;
    RETURN created;
END;
$function$
;
CREATE OR REPLACE FUNCTION spy.url_host(p_url text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$ SELECT lower(COALESCE(substring(p_url FROM '^[a-zA-Z]+://([^/?#]+)'), '')) $function$
;
CREATE OR REPLACE FUNCTION spy.url_path(p_url text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
AS $function$ SELECT COALESCE(NULLIF(substring(p_url FROM '^[a-zA-Z]+://[^/?#]+([^?#]*)'), ''), '/') $function$
;
CREATE OR REPLACE FUNCTION spy.link_key(p_url text, p_campaign text, p_item text)
 RETURNS uuid
 LANGUAGE sql
 IMMUTABLE
AS $function$
    SELECT md5(spy.url_host(p_url) || '|' || spy.url_path(p_url) || '|' ||
               COALESCE(p_campaign, '') || '|' || COALESCE(p_item, ''))::uuid
$function$
;
INSERT INTO spy.network (id, code, name) VALUES (1, 'taboola', 'Taboola'), (2, 'newsbreak', 'NewsBreak Ads');
INSERT INTO spy.device (id, code) VALUES (1, 'desktop'), (2, 'phone');
